/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the LicenseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LicenseResponse{}

// LicenseResponse The response of a license request.
type LicenseResponse struct {
	// True if the Camunda license is valid, false if otherwise
	ValidLicense bool `json:"validLicense"`
	// Will return the license type property of the Camunda license
	LicenseType string `json:"licenseType"`
	// Will be false when a license contains a non-commerical=true property
	IsCommercial bool `json:"isCommercial"`
	// The date when the Camunda license expires
	ExpiresAt NullableTime `json:"expiresAt"`
}

type _LicenseResponse LicenseResponse

// NewLicenseResponse instantiates a new LicenseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicenseResponse(validLicense bool, licenseType string, isCommercial bool, expiresAt NullableTime) *LicenseResponse {
	this := LicenseResponse{}
	this.ValidLicense = validLicense
	this.LicenseType = licenseType
	this.IsCommercial = isCommercial
	this.ExpiresAt = expiresAt
	return &this
}

// NewLicenseResponseWithDefaults instantiates a new LicenseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicenseResponseWithDefaults() *LicenseResponse {
	this := LicenseResponse{}
	return &this
}

// GetValidLicense returns the ValidLicense field value
func (o *LicenseResponse) GetValidLicense() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ValidLicense
}

// GetValidLicenseOk returns a tuple with the ValidLicense field value
// and a boolean to check if the value has been set.
func (o *LicenseResponse) GetValidLicenseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidLicense, true
}

// SetValidLicense sets field value
func (o *LicenseResponse) SetValidLicense(v bool) {
	o.ValidLicense = v
}

// GetLicenseType returns the LicenseType field value
func (o *LicenseResponse) GetLicenseType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LicenseType
}

// GetLicenseTypeOk returns a tuple with the LicenseType field value
// and a boolean to check if the value has been set.
func (o *LicenseResponse) GetLicenseTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LicenseType, true
}

// SetLicenseType sets field value
func (o *LicenseResponse) SetLicenseType(v string) {
	o.LicenseType = v
}

// GetIsCommercial returns the IsCommercial field value
func (o *LicenseResponse) GetIsCommercial() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsCommercial
}

// GetIsCommercialOk returns a tuple with the IsCommercial field value
// and a boolean to check if the value has been set.
func (o *LicenseResponse) GetIsCommercialOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsCommercial, true
}

// SetIsCommercial sets field value
func (o *LicenseResponse) SetIsCommercial(v bool) {
	o.IsCommercial = v
}

// GetExpiresAt returns the ExpiresAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *LicenseResponse) GetExpiresAt() time.Time {
	if o == nil || o.ExpiresAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LicenseResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// SetExpiresAt sets field value
func (o *LicenseResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}

func (o LicenseResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LicenseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["validLicense"] = o.ValidLicense
	toSerialize["licenseType"] = o.LicenseType
	toSerialize["isCommercial"] = o.IsCommercial
	toSerialize["expiresAt"] = o.ExpiresAt.Get()
	return toSerialize, nil
}

func (o *LicenseResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"validLicense",
		"licenseType",
		"isCommercial",
		"expiresAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLicenseResponse := _LicenseResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLicenseResponse)

	if err != nil {
		return err
	}

	*o = LicenseResponse(varLicenseResponse)

	return err
}

type NullableLicenseResponse struct {
	value *LicenseResponse
	isSet bool
}

func (v NullableLicenseResponse) Get() *LicenseResponse {
	return v.value
}

func (v *NullableLicenseResponse) Set(val *LicenseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLicenseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLicenseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicenseResponse(val *LicenseResponse) *NullableLicenseResponse {
	return &NullableLicenseResponse{value: val, isSet: true}
}

func (v NullableLicenseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicenseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
