/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// MessageSubscriptionTypeFilterProperty - MessageSubscriptionTypeEnum with full advanced search capabilities.
type MessageSubscriptionTypeFilterProperty struct {
	AdvancedMessageSubscriptionTypeFilter *AdvancedMessageSubscriptionTypeFilter
	MessageSubscriptionTypeExactMatch     *MessageSubscriptionTypeExactMatch
}

// AdvancedMessageSubscriptionTypeFilterAsMessageSubscriptionTypeFilterProperty is a convenience function that returns AdvancedMessageSubscriptionTypeFilter wrapped in MessageSubscriptionTypeFilterProperty
func AdvancedMessageSubscriptionTypeFilterAsMessageSubscriptionTypeFilterProperty(v *AdvancedMessageSubscriptionTypeFilter) MessageSubscriptionTypeFilterProperty {
	return MessageSubscriptionTypeFilterProperty{
		AdvancedMessageSubscriptionTypeFilter: v,
	}
}

// MessageSubscriptionTypeExactMatchAsMessageSubscriptionTypeFilterProperty is a convenience function that returns MessageSubscriptionTypeExactMatch wrapped in MessageSubscriptionTypeFilterProperty
func MessageSubscriptionTypeExactMatchAsMessageSubscriptionTypeFilterProperty(v *MessageSubscriptionTypeExactMatch) MessageSubscriptionTypeFilterProperty {
	return MessageSubscriptionTypeFilterProperty{
		MessageSubscriptionTypeExactMatch: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *MessageSubscriptionTypeFilterProperty) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AdvancedMessageSubscriptionTypeFilter
	err = json.Unmarshal(data, &dst.AdvancedMessageSubscriptionTypeFilter)
	if err == nil {
		jsonAdvancedMessageSubscriptionTypeFilter, _ := json.Marshal(dst.AdvancedMessageSubscriptionTypeFilter)
		if string(jsonAdvancedMessageSubscriptionTypeFilter) == "{}" { // empty struct
			dst.AdvancedMessageSubscriptionTypeFilter = nil
		} else {
			match++
		}
	} else {
		dst.AdvancedMessageSubscriptionTypeFilter = nil
	}

	// try to unmarshal data into MessageSubscriptionTypeExactMatch
	err = json.Unmarshal(data, &dst.MessageSubscriptionTypeExactMatch)
	if err == nil {
		jsonMessageSubscriptionTypeExactMatch, _ := json.Marshal(dst.MessageSubscriptionTypeExactMatch)
		if string(jsonMessageSubscriptionTypeExactMatch) == "{}" { // empty struct
			dst.MessageSubscriptionTypeExactMatch = nil
		} else {
			match++
		}
	} else {
		dst.MessageSubscriptionTypeExactMatch = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AdvancedMessageSubscriptionTypeFilter = nil
		dst.MessageSubscriptionTypeExactMatch = nil

		return fmt.Errorf("data matches more than one schema in oneOf(MessageSubscriptionTypeFilterProperty)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(MessageSubscriptionTypeFilterProperty)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MessageSubscriptionTypeFilterProperty) MarshalJSON() ([]byte, error) {
	if src.AdvancedMessageSubscriptionTypeFilter != nil {
		return json.Marshal(&src.AdvancedMessageSubscriptionTypeFilter)
	}

	if src.MessageSubscriptionTypeExactMatch != nil {
		return json.Marshal(&src.MessageSubscriptionTypeExactMatch)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MessageSubscriptionTypeFilterProperty) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.AdvancedMessageSubscriptionTypeFilter != nil {
		return obj.AdvancedMessageSubscriptionTypeFilter
	}

	if obj.MessageSubscriptionTypeExactMatch != nil {
		return obj.MessageSubscriptionTypeExactMatch
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj MessageSubscriptionTypeFilterProperty) GetActualInstanceValue() interface{} {
	if obj.AdvancedMessageSubscriptionTypeFilter != nil {
		return *obj.AdvancedMessageSubscriptionTypeFilter
	}

	if obj.MessageSubscriptionTypeExactMatch != nil {
		return *obj.MessageSubscriptionTypeExactMatch
	}

	// all schemas are nil
	return nil
}

type NullableMessageSubscriptionTypeFilterProperty struct {
	value *MessageSubscriptionTypeFilterProperty
	isSet bool
}

func (v NullableMessageSubscriptionTypeFilterProperty) Get() *MessageSubscriptionTypeFilterProperty {
	return v.value
}

func (v *NullableMessageSubscriptionTypeFilterProperty) Set(val *MessageSubscriptionTypeFilterProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageSubscriptionTypeFilterProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageSubscriptionTypeFilterProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageSubscriptionTypeFilterProperty(val *MessageSubscriptionTypeFilterProperty) *NullableMessageSubscriptionTypeFilterProperty {
	return &NullableMessageSubscriptionTypeFilterProperty{value: val, isSet: true}
}

func (v NullableMessageSubscriptionTypeFilterProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageSubscriptionTypeFilterProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
