/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SearchQueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchQueryResponse{}

// SearchQueryResponse struct for SearchQueryResponse
type SearchQueryResponse struct {
	Page SearchQueryPageResponse `json:"page"`
}

type _SearchQueryResponse SearchQueryResponse

// NewSearchQueryResponse instantiates a new SearchQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchQueryResponse(page SearchQueryPageResponse) *SearchQueryResponse {
	this := SearchQueryResponse{}
	this.Page = page
	return &this
}

// NewSearchQueryResponseWithDefaults instantiates a new SearchQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchQueryResponseWithDefaults() *SearchQueryResponse {
	this := SearchQueryResponse{}
	return &this
}

// GetPage returns the Page field value
func (o *SearchQueryResponse) GetPage() SearchQueryPageResponse {
	if o == nil {
		var ret SearchQueryPageResponse
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *SearchQueryResponse) GetPageOk() (*SearchQueryPageResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *SearchQueryResponse) SetPage(v SearchQueryPageResponse) {
	o.Page = v
}

func (o SearchQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchQueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	return toSerialize, nil
}

func (o *SearchQueryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchQueryResponse := _SearchQueryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchQueryResponse)

	if err != nil {
		return err
	}

	*o = SearchQueryResponse(varSearchQueryResponse)

	return err
}

type NullableSearchQueryResponse struct {
	value *SearchQueryResponse
	isSet bool
}

func (v NullableSearchQueryResponse) Get() *SearchQueryResponse {
	return v.value
}

func (v *NullableSearchQueryResponse) Set(val *SearchQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchQueryResponse(val *SearchQueryResponse) *NullableSearchQueryResponse {
	return &NullableSearchQueryResponse{value: val, isSet: true}
}

func (v NullableSearchQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
