/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserTaskAuditLogSearchQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserTaskAuditLogSearchQueryRequest{}

// UserTaskAuditLogSearchQueryRequest struct for UserTaskAuditLogSearchQueryRequest
type UserTaskAuditLogSearchQueryRequest struct {
	// Pagination criteria.
	Page *SearchQueryPageRequest `json:"page,omitempty"`
	// Sort field criteria.
	Sort   []AuditLogSearchQuerySortRequest `json:"sort,omitempty"`
	Filter *UserTaskAuditLogFilter          `json:"filter,omitempty"`
}

// NewUserTaskAuditLogSearchQueryRequest instantiates a new UserTaskAuditLogSearchQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserTaskAuditLogSearchQueryRequest() *UserTaskAuditLogSearchQueryRequest {
	this := UserTaskAuditLogSearchQueryRequest{}
	return &this
}

// NewUserTaskAuditLogSearchQueryRequestWithDefaults instantiates a new UserTaskAuditLogSearchQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserTaskAuditLogSearchQueryRequestWithDefaults() *UserTaskAuditLogSearchQueryRequest {
	this := UserTaskAuditLogSearchQueryRequest{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *UserTaskAuditLogSearchQueryRequest) GetPage() SearchQueryPageRequest {
	if o == nil || IsNil(o.Page) {
		var ret SearchQueryPageRequest
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserTaskAuditLogSearchQueryRequest) GetPageOk() (*SearchQueryPageRequest, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *UserTaskAuditLogSearchQueryRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given SearchQueryPageRequest and assigns it to the Page field.
func (o *UserTaskAuditLogSearchQueryRequest) SetPage(v SearchQueryPageRequest) {
	o.Page = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *UserTaskAuditLogSearchQueryRequest) GetSort() []AuditLogSearchQuerySortRequest {
	if o == nil || IsNil(o.Sort) {
		var ret []AuditLogSearchQuerySortRequest
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserTaskAuditLogSearchQueryRequest) GetSortOk() ([]AuditLogSearchQuerySortRequest, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *UserTaskAuditLogSearchQueryRequest) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []AuditLogSearchQuerySortRequest and assigns it to the Sort field.
func (o *UserTaskAuditLogSearchQueryRequest) SetSort(v []AuditLogSearchQuerySortRequest) {
	o.Sort = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *UserTaskAuditLogSearchQueryRequest) GetFilter() UserTaskAuditLogFilter {
	if o == nil || IsNil(o.Filter) {
		var ret UserTaskAuditLogFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserTaskAuditLogSearchQueryRequest) GetFilterOk() (*UserTaskAuditLogFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *UserTaskAuditLogSearchQueryRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given UserTaskAuditLogFilter and assigns it to the Filter field.
func (o *UserTaskAuditLogSearchQueryRequest) SetFilter(v UserTaskAuditLogFilter) {
	o.Filter = &v
}

func (o UserTaskAuditLogSearchQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserTaskAuditLogSearchQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	return toSerialize, nil
}

type NullableUserTaskAuditLogSearchQueryRequest struct {
	value *UserTaskAuditLogSearchQueryRequest
	isSet bool
}

func (v NullableUserTaskAuditLogSearchQueryRequest) Get() *UserTaskAuditLogSearchQueryRequest {
	return v.value
}

func (v *NullableUserTaskAuditLogSearchQueryRequest) Set(val *UserTaskAuditLogSearchQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTaskAuditLogSearchQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTaskAuditLogSearchQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTaskAuditLogSearchQueryRequest(val *UserTaskAuditLogSearchQueryRequest) *NullableUserTaskAuditLogSearchQueryRequest {
	return &NullableUserTaskAuditLogSearchQueryRequest{value: val, isSet: true}
}

func (v NullableUserTaskAuditLogSearchQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTaskAuditLogSearchQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
