/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the JobFailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobFailRequest{}

// JobFailRequest struct for JobFailRequest
type JobFailRequest struct {
	// The amount of retries the job should have left
	Retries *int32 `json:"retries,omitempty"`
	// An optional error message describing why the job failed; if not provided, an empty string is used.
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// An optional retry back off for the failed job. The job will not be retryable before the current time plus the back off time. The default is 0 which means the job is retryable immediately.
	RetryBackOff *int64 `json:"retryBackOff,omitempty"`
	// JSON object that will instantiate the variables at the local scope of the job's associated task.
	Variables map[string]interface{} `json:"variables,omitempty"`
	// The token identifying a leased job's activation, obtained from `ActivatedJobResult.leaseToken`. For a leased job, the matching token must be supplied to prove the command comes from the worker that holds the current lease; a command with no token is rejected. A command carrying a stale token is likewise rejected, fencing the job against a superseded activation (for example, after the job timed out or failed and was re-activated by another worker). A job that was activated without a lease requires no token.
	LeaseToken NullableString `json:"leaseToken,omitempty"`
}

// NewJobFailRequest instantiates a new JobFailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobFailRequest() *JobFailRequest {
	this := JobFailRequest{}
	var retries int32 = 0
	this.Retries = &retries
	var retryBackOff int64 = 0
	this.RetryBackOff = &retryBackOff
	return &this
}

// NewJobFailRequestWithDefaults instantiates a new JobFailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobFailRequestWithDefaults() *JobFailRequest {
	this := JobFailRequest{}
	var retries int32 = 0
	this.Retries = &retries
	var retryBackOff int64 = 0
	this.RetryBackOff = &retryBackOff
	return &this
}

// GetRetries returns the Retries field value if set, zero value otherwise.
func (o *JobFailRequest) GetRetries() int32 {
	if o == nil || IsNil(o.Retries) {
		var ret int32
		return ret
	}
	return *o.Retries
}

// GetRetriesOk returns a tuple with the Retries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobFailRequest) GetRetriesOk() (*int32, bool) {
	if o == nil || IsNil(o.Retries) {
		return nil, false
	}
	return o.Retries, true
}

// HasRetries returns a boolean if a field has been set.
func (o *JobFailRequest) HasRetries() bool {
	if o != nil && !IsNil(o.Retries) {
		return true
	}

	return false
}

// SetRetries gets a reference to the given int32 and assigns it to the Retries field.
func (o *JobFailRequest) SetRetries(v int32) {
	o.Retries = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *JobFailRequest) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobFailRequest) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *JobFailRequest) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *JobFailRequest) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetRetryBackOff returns the RetryBackOff field value if set, zero value otherwise.
func (o *JobFailRequest) GetRetryBackOff() int64 {
	if o == nil || IsNil(o.RetryBackOff) {
		var ret int64
		return ret
	}
	return *o.RetryBackOff
}

// GetRetryBackOffOk returns a tuple with the RetryBackOff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobFailRequest) GetRetryBackOffOk() (*int64, bool) {
	if o == nil || IsNil(o.RetryBackOff) {
		return nil, false
	}
	return o.RetryBackOff, true
}

// HasRetryBackOff returns a boolean if a field has been set.
func (o *JobFailRequest) HasRetryBackOff() bool {
	if o != nil && !IsNil(o.RetryBackOff) {
		return true
	}

	return false
}

// SetRetryBackOff gets a reference to the given int64 and assigns it to the RetryBackOff field.
func (o *JobFailRequest) SetRetryBackOff(v int64) {
	o.RetryBackOff = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *JobFailRequest) GetVariables() map[string]interface{} {
	if o == nil || IsNil(o.Variables) {
		var ret map[string]interface{}
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobFailRequest) GetVariablesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Variables) {
		return map[string]interface{}{}, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *JobFailRequest) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]interface{} and assigns it to the Variables field.
func (o *JobFailRequest) SetVariables(v map[string]interface{}) {
	o.Variables = v
}

// GetLeaseToken returns the LeaseToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobFailRequest) GetLeaseToken() string {
	if o == nil || IsNil(o.LeaseToken.Get()) {
		var ret string
		return ret
	}
	return *o.LeaseToken.Get()
}

// GetLeaseTokenOk returns a tuple with the LeaseToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobFailRequest) GetLeaseTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LeaseToken.Get(), o.LeaseToken.IsSet()
}

// HasLeaseToken returns a boolean if a field has been set.
func (o *JobFailRequest) HasLeaseToken() bool {
	if o != nil && o.LeaseToken.IsSet() {
		return true
	}

	return false
}

// SetLeaseToken gets a reference to the given NullableString and assigns it to the LeaseToken field.
func (o *JobFailRequest) SetLeaseToken(v string) {
	o.LeaseToken.Set(&v)
}

// SetLeaseTokenNil sets the value for LeaseToken to be an explicit nil
func (o *JobFailRequest) SetLeaseTokenNil() {
	o.LeaseToken.Set(nil)
}

// UnsetLeaseToken ensures that no value is present for LeaseToken, not even an explicit nil
func (o *JobFailRequest) UnsetLeaseToken() {
	o.LeaseToken.Unset()
}

func (o JobFailRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobFailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Retries) {
		toSerialize["retries"] = o.Retries
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.RetryBackOff) {
		toSerialize["retryBackOff"] = o.RetryBackOff
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	if o.LeaseToken.IsSet() {
		toSerialize["leaseToken"] = o.LeaseToken.Get()
	}
	return toSerialize, nil
}

type NullableJobFailRequest struct {
	value *JobFailRequest
	isSet bool
}

func (v NullableJobFailRequest) Get() *JobFailRequest {
	return v.value
}

func (v *NullableJobFailRequest) Set(val *JobFailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobFailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobFailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobFailRequest(val *JobFailRequest) *NullableJobFailRequest {
	return &NullableJobFailRequest{value: val, isSet: true}
}

func (v NullableJobFailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobFailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
