/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProcessInstanceFilterFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessInstanceFilterFields{}

// ProcessInstanceFilterFields struct for ProcessInstanceFilterFields
type ProcessInstanceFilterFields struct {
	// The start date.
	StartDate *DateTimeFilterProperty `json:"startDate,omitempty"`
	// The end date.
	EndDate *DateTimeFilterProperty `json:"endDate,omitempty"`
	// The process instance state.
	State *ProcessInstanceStateFilterProperty `json:"state,omitempty"`
	// Whether this process instance has a related incident or not.
	HasIncident *bool `json:"hasIncident,omitempty"`
	// The tenant id.
	TenantId *StringFilterProperty `json:"tenantId,omitempty"`
	// The process instance variables.
	Variables []VariableValueFilterProperty `json:"variables,omitempty"`
	// The key of this process instance.
	ProcessInstanceKey *ProcessInstanceKeyFilterProperty `json:"processInstanceKey,omitempty"`
	// The parent process instance key.
	ParentProcessInstanceKey *ProcessInstanceKeyFilterProperty `json:"parentProcessInstanceKey,omitempty"`
	// The parent element instance key.
	ParentElementInstanceKey *ElementInstanceKeyFilterProperty `json:"parentElementInstanceKey,omitempty"`
	// The batch operation id. **Deprecated**: Use `batchOperationKey` instead. This field will be removed in a future release. If both `batchOperationId` and `batchOperationKey` are provided, the request will be rejected with a 400 error.
	// Deprecated
	BatchOperationId *StringFilterProperty `json:"batchOperationId,omitempty"`
	// The batch operation key.
	BatchOperationKey *StringFilterProperty `json:"batchOperationKey,omitempty"`
	// The error message related to the process.
	ErrorMessage *StringFilterProperty `json:"errorMessage,omitempty"`
	// Whether the process has failed jobs with retries left.
	HasRetriesLeft *bool `json:"hasRetriesLeft,omitempty"`
	// The state of the element instances associated with the process instance.
	ElementInstanceState *ElementInstanceStateFilterProperty `json:"elementInstanceState,omitempty"`
	// The element id associated with the process instance.
	ElementId *StringFilterProperty `json:"elementId,omitempty"`
	// Whether the element instance has an incident or not.
	HasElementInstanceIncident *bool `json:"hasElementInstanceIncident,omitempty"`
	// The incident error hash code, associated with this process.
	IncidentErrorHashCode *IntegerFilterProperty `json:"incidentErrorHashCode,omitempty"`
	// List of tags. Tags need to start with a letter; then alphanumerics, `_`, `-`, `:`, or `.`; length ≤ 100.
	Tags []string `json:"tags,omitempty"`
	// The business id associated with the process instance.
	BusinessId *StringFilterProperty `json:"businessId,omitempty"`
	// The process definition id.
	ProcessDefinitionId *StringFilterProperty `json:"processDefinitionId,omitempty"`
	// The process definition name.
	ProcessDefinitionName *StringFilterProperty `json:"processDefinitionName,omitempty"`
	// The process definition version.
	ProcessDefinitionVersion *IntegerFilterProperty `json:"processDefinitionVersion,omitempty"`
	// The process definition version tag.
	ProcessDefinitionVersionTag *StringFilterProperty `json:"processDefinitionVersionTag,omitempty"`
	// The process definition key.
	ProcessDefinitionKey *ProcessDefinitionKeyFilterProperty `json:"processDefinitionKey,omitempty"`
}

// NewProcessInstanceFilterFields instantiates a new ProcessInstanceFilterFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessInstanceFilterFields() *ProcessInstanceFilterFields {
	this := ProcessInstanceFilterFields{}
	return &this
}

// NewProcessInstanceFilterFieldsWithDefaults instantiates a new ProcessInstanceFilterFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessInstanceFilterFieldsWithDefaults() *ProcessInstanceFilterFields {
	this := ProcessInstanceFilterFields{}
	return &this
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetStartDate() DateTimeFilterProperty {
	if o == nil || IsNil(o.StartDate) {
		var ret DateTimeFilterProperty
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetStartDateOk() (*DateTimeFilterProperty, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given DateTimeFilterProperty and assigns it to the StartDate field.
func (o *ProcessInstanceFilterFields) SetStartDate(v DateTimeFilterProperty) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetEndDate() DateTimeFilterProperty {
	if o == nil || IsNil(o.EndDate) {
		var ret DateTimeFilterProperty
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetEndDateOk() (*DateTimeFilterProperty, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given DateTimeFilterProperty and assigns it to the EndDate field.
func (o *ProcessInstanceFilterFields) SetEndDate(v DateTimeFilterProperty) {
	o.EndDate = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetState() ProcessInstanceStateFilterProperty {
	if o == nil || IsNil(o.State) {
		var ret ProcessInstanceStateFilterProperty
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetStateOk() (*ProcessInstanceStateFilterProperty, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given ProcessInstanceStateFilterProperty and assigns it to the State field.
func (o *ProcessInstanceFilterFields) SetState(v ProcessInstanceStateFilterProperty) {
	o.State = &v
}

// GetHasIncident returns the HasIncident field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetHasIncident() bool {
	if o == nil || IsNil(o.HasIncident) {
		var ret bool
		return ret
	}
	return *o.HasIncident
}

// GetHasIncidentOk returns a tuple with the HasIncident field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetHasIncidentOk() (*bool, bool) {
	if o == nil || IsNil(o.HasIncident) {
		return nil, false
	}
	return o.HasIncident, true
}

// HasHasIncident returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasHasIncident() bool {
	if o != nil && !IsNil(o.HasIncident) {
		return true
	}

	return false
}

// SetHasIncident gets a reference to the given bool and assigns it to the HasIncident field.
func (o *ProcessInstanceFilterFields) SetHasIncident(v bool) {
	o.HasIncident = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetTenantId() StringFilterProperty {
	if o == nil || IsNil(o.TenantId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetTenantIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given StringFilterProperty and assigns it to the TenantId field.
func (o *ProcessInstanceFilterFields) SetTenantId(v StringFilterProperty) {
	o.TenantId = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetVariables() []VariableValueFilterProperty {
	if o == nil || IsNil(o.Variables) {
		var ret []VariableValueFilterProperty
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetVariablesOk() ([]VariableValueFilterProperty, bool) {
	if o == nil || IsNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []VariableValueFilterProperty and assigns it to the Variables field.
func (o *ProcessInstanceFilterFields) SetVariables(v []VariableValueFilterProperty) {
	o.Variables = v
}

// GetProcessInstanceKey returns the ProcessInstanceKey field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetProcessInstanceKey() ProcessInstanceKeyFilterProperty {
	if o == nil || IsNil(o.ProcessInstanceKey) {
		var ret ProcessInstanceKeyFilterProperty
		return ret
	}
	return *o.ProcessInstanceKey
}

// GetProcessInstanceKeyOk returns a tuple with the ProcessInstanceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetProcessInstanceKeyOk() (*ProcessInstanceKeyFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessInstanceKey) {
		return nil, false
	}
	return o.ProcessInstanceKey, true
}

// HasProcessInstanceKey returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasProcessInstanceKey() bool {
	if o != nil && !IsNil(o.ProcessInstanceKey) {
		return true
	}

	return false
}

// SetProcessInstanceKey gets a reference to the given ProcessInstanceKeyFilterProperty and assigns it to the ProcessInstanceKey field.
func (o *ProcessInstanceFilterFields) SetProcessInstanceKey(v ProcessInstanceKeyFilterProperty) {
	o.ProcessInstanceKey = &v
}

// GetParentProcessInstanceKey returns the ParentProcessInstanceKey field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetParentProcessInstanceKey() ProcessInstanceKeyFilterProperty {
	if o == nil || IsNil(o.ParentProcessInstanceKey) {
		var ret ProcessInstanceKeyFilterProperty
		return ret
	}
	return *o.ParentProcessInstanceKey
}

// GetParentProcessInstanceKeyOk returns a tuple with the ParentProcessInstanceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetParentProcessInstanceKeyOk() (*ProcessInstanceKeyFilterProperty, bool) {
	if o == nil || IsNil(o.ParentProcessInstanceKey) {
		return nil, false
	}
	return o.ParentProcessInstanceKey, true
}

// HasParentProcessInstanceKey returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasParentProcessInstanceKey() bool {
	if o != nil && !IsNil(o.ParentProcessInstanceKey) {
		return true
	}

	return false
}

// SetParentProcessInstanceKey gets a reference to the given ProcessInstanceKeyFilterProperty and assigns it to the ParentProcessInstanceKey field.
func (o *ProcessInstanceFilterFields) SetParentProcessInstanceKey(v ProcessInstanceKeyFilterProperty) {
	o.ParentProcessInstanceKey = &v
}

// GetParentElementInstanceKey returns the ParentElementInstanceKey field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetParentElementInstanceKey() ElementInstanceKeyFilterProperty {
	if o == nil || IsNil(o.ParentElementInstanceKey) {
		var ret ElementInstanceKeyFilterProperty
		return ret
	}
	return *o.ParentElementInstanceKey
}

// GetParentElementInstanceKeyOk returns a tuple with the ParentElementInstanceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetParentElementInstanceKeyOk() (*ElementInstanceKeyFilterProperty, bool) {
	if o == nil || IsNil(o.ParentElementInstanceKey) {
		return nil, false
	}
	return o.ParentElementInstanceKey, true
}

// HasParentElementInstanceKey returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasParentElementInstanceKey() bool {
	if o != nil && !IsNil(o.ParentElementInstanceKey) {
		return true
	}

	return false
}

// SetParentElementInstanceKey gets a reference to the given ElementInstanceKeyFilterProperty and assigns it to the ParentElementInstanceKey field.
func (o *ProcessInstanceFilterFields) SetParentElementInstanceKey(v ElementInstanceKeyFilterProperty) {
	o.ParentElementInstanceKey = &v
}

// GetBatchOperationId returns the BatchOperationId field value if set, zero value otherwise.
// Deprecated
func (o *ProcessInstanceFilterFields) GetBatchOperationId() StringFilterProperty {
	if o == nil || IsNil(o.BatchOperationId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.BatchOperationId
}

// GetBatchOperationIdOk returns a tuple with the BatchOperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *ProcessInstanceFilterFields) GetBatchOperationIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.BatchOperationId) {
		return nil, false
	}
	return o.BatchOperationId, true
}

// HasBatchOperationId returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasBatchOperationId() bool {
	if o != nil && !IsNil(o.BatchOperationId) {
		return true
	}

	return false
}

// SetBatchOperationId gets a reference to the given StringFilterProperty and assigns it to the BatchOperationId field.
// Deprecated
func (o *ProcessInstanceFilterFields) SetBatchOperationId(v StringFilterProperty) {
	o.BatchOperationId = &v
}

// GetBatchOperationKey returns the BatchOperationKey field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetBatchOperationKey() StringFilterProperty {
	if o == nil || IsNil(o.BatchOperationKey) {
		var ret StringFilterProperty
		return ret
	}
	return *o.BatchOperationKey
}

// GetBatchOperationKeyOk returns a tuple with the BatchOperationKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetBatchOperationKeyOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.BatchOperationKey) {
		return nil, false
	}
	return o.BatchOperationKey, true
}

// HasBatchOperationKey returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasBatchOperationKey() bool {
	if o != nil && !IsNil(o.BatchOperationKey) {
		return true
	}

	return false
}

// SetBatchOperationKey gets a reference to the given StringFilterProperty and assigns it to the BatchOperationKey field.
func (o *ProcessInstanceFilterFields) SetBatchOperationKey(v StringFilterProperty) {
	o.BatchOperationKey = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetErrorMessage() StringFilterProperty {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret StringFilterProperty
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetErrorMessageOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given StringFilterProperty and assigns it to the ErrorMessage field.
func (o *ProcessInstanceFilterFields) SetErrorMessage(v StringFilterProperty) {
	o.ErrorMessage = &v
}

// GetHasRetriesLeft returns the HasRetriesLeft field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetHasRetriesLeft() bool {
	if o == nil || IsNil(o.HasRetriesLeft) {
		var ret bool
		return ret
	}
	return *o.HasRetriesLeft
}

// GetHasRetriesLeftOk returns a tuple with the HasRetriesLeft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetHasRetriesLeftOk() (*bool, bool) {
	if o == nil || IsNil(o.HasRetriesLeft) {
		return nil, false
	}
	return o.HasRetriesLeft, true
}

// HasHasRetriesLeft returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasHasRetriesLeft() bool {
	if o != nil && !IsNil(o.HasRetriesLeft) {
		return true
	}

	return false
}

// SetHasRetriesLeft gets a reference to the given bool and assigns it to the HasRetriesLeft field.
func (o *ProcessInstanceFilterFields) SetHasRetriesLeft(v bool) {
	o.HasRetriesLeft = &v
}

// GetElementInstanceState returns the ElementInstanceState field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetElementInstanceState() ElementInstanceStateFilterProperty {
	if o == nil || IsNil(o.ElementInstanceState) {
		var ret ElementInstanceStateFilterProperty
		return ret
	}
	return *o.ElementInstanceState
}

// GetElementInstanceStateOk returns a tuple with the ElementInstanceState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetElementInstanceStateOk() (*ElementInstanceStateFilterProperty, bool) {
	if o == nil || IsNil(o.ElementInstanceState) {
		return nil, false
	}
	return o.ElementInstanceState, true
}

// HasElementInstanceState returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasElementInstanceState() bool {
	if o != nil && !IsNil(o.ElementInstanceState) {
		return true
	}

	return false
}

// SetElementInstanceState gets a reference to the given ElementInstanceStateFilterProperty and assigns it to the ElementInstanceState field.
func (o *ProcessInstanceFilterFields) SetElementInstanceState(v ElementInstanceStateFilterProperty) {
	o.ElementInstanceState = &v
}

// GetElementId returns the ElementId field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetElementId() StringFilterProperty {
	if o == nil || IsNil(o.ElementId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.ElementId
}

// GetElementIdOk returns a tuple with the ElementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetElementIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.ElementId) {
		return nil, false
	}
	return o.ElementId, true
}

// HasElementId returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasElementId() bool {
	if o != nil && !IsNil(o.ElementId) {
		return true
	}

	return false
}

// SetElementId gets a reference to the given StringFilterProperty and assigns it to the ElementId field.
func (o *ProcessInstanceFilterFields) SetElementId(v StringFilterProperty) {
	o.ElementId = &v
}

// GetHasElementInstanceIncident returns the HasElementInstanceIncident field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetHasElementInstanceIncident() bool {
	if o == nil || IsNil(o.HasElementInstanceIncident) {
		var ret bool
		return ret
	}
	return *o.HasElementInstanceIncident
}

// GetHasElementInstanceIncidentOk returns a tuple with the HasElementInstanceIncident field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetHasElementInstanceIncidentOk() (*bool, bool) {
	if o == nil || IsNil(o.HasElementInstanceIncident) {
		return nil, false
	}
	return o.HasElementInstanceIncident, true
}

// HasHasElementInstanceIncident returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasHasElementInstanceIncident() bool {
	if o != nil && !IsNil(o.HasElementInstanceIncident) {
		return true
	}

	return false
}

// SetHasElementInstanceIncident gets a reference to the given bool and assigns it to the HasElementInstanceIncident field.
func (o *ProcessInstanceFilterFields) SetHasElementInstanceIncident(v bool) {
	o.HasElementInstanceIncident = &v
}

// GetIncidentErrorHashCode returns the IncidentErrorHashCode field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetIncidentErrorHashCode() IntegerFilterProperty {
	if o == nil || IsNil(o.IncidentErrorHashCode) {
		var ret IntegerFilterProperty
		return ret
	}
	return *o.IncidentErrorHashCode
}

// GetIncidentErrorHashCodeOk returns a tuple with the IncidentErrorHashCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetIncidentErrorHashCodeOk() (*IntegerFilterProperty, bool) {
	if o == nil || IsNil(o.IncidentErrorHashCode) {
		return nil, false
	}
	return o.IncidentErrorHashCode, true
}

// HasIncidentErrorHashCode returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasIncidentErrorHashCode() bool {
	if o != nil && !IsNil(o.IncidentErrorHashCode) {
		return true
	}

	return false
}

// SetIncidentErrorHashCode gets a reference to the given IntegerFilterProperty and assigns it to the IncidentErrorHashCode field.
func (o *ProcessInstanceFilterFields) SetIncidentErrorHashCode(v IntegerFilterProperty) {
	o.IncidentErrorHashCode = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ProcessInstanceFilterFields) SetTags(v []string) {
	o.Tags = v
}

// GetBusinessId returns the BusinessId field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetBusinessId() StringFilterProperty {
	if o == nil || IsNil(o.BusinessId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetBusinessIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.BusinessId) {
		return nil, false
	}
	return o.BusinessId, true
}

// HasBusinessId returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasBusinessId() bool {
	if o != nil && !IsNil(o.BusinessId) {
		return true
	}

	return false
}

// SetBusinessId gets a reference to the given StringFilterProperty and assigns it to the BusinessId field.
func (o *ProcessInstanceFilterFields) SetBusinessId(v StringFilterProperty) {
	o.BusinessId = &v
}

// GetProcessDefinitionId returns the ProcessDefinitionId field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionId() StringFilterProperty {
	if o == nil || IsNil(o.ProcessDefinitionId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.ProcessDefinitionId
}

// GetProcessDefinitionIdOk returns a tuple with the ProcessDefinitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessDefinitionId) {
		return nil, false
	}
	return o.ProcessDefinitionId, true
}

// HasProcessDefinitionId returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasProcessDefinitionId() bool {
	if o != nil && !IsNil(o.ProcessDefinitionId) {
		return true
	}

	return false
}

// SetProcessDefinitionId gets a reference to the given StringFilterProperty and assigns it to the ProcessDefinitionId field.
func (o *ProcessInstanceFilterFields) SetProcessDefinitionId(v StringFilterProperty) {
	o.ProcessDefinitionId = &v
}

// GetProcessDefinitionName returns the ProcessDefinitionName field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionName() StringFilterProperty {
	if o == nil || IsNil(o.ProcessDefinitionName) {
		var ret StringFilterProperty
		return ret
	}
	return *o.ProcessDefinitionName
}

// GetProcessDefinitionNameOk returns a tuple with the ProcessDefinitionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionNameOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessDefinitionName) {
		return nil, false
	}
	return o.ProcessDefinitionName, true
}

// HasProcessDefinitionName returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasProcessDefinitionName() bool {
	if o != nil && !IsNil(o.ProcessDefinitionName) {
		return true
	}

	return false
}

// SetProcessDefinitionName gets a reference to the given StringFilterProperty and assigns it to the ProcessDefinitionName field.
func (o *ProcessInstanceFilterFields) SetProcessDefinitionName(v StringFilterProperty) {
	o.ProcessDefinitionName = &v
}

// GetProcessDefinitionVersion returns the ProcessDefinitionVersion field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionVersion() IntegerFilterProperty {
	if o == nil || IsNil(o.ProcessDefinitionVersion) {
		var ret IntegerFilterProperty
		return ret
	}
	return *o.ProcessDefinitionVersion
}

// GetProcessDefinitionVersionOk returns a tuple with the ProcessDefinitionVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionVersionOk() (*IntegerFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessDefinitionVersion) {
		return nil, false
	}
	return o.ProcessDefinitionVersion, true
}

// HasProcessDefinitionVersion returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasProcessDefinitionVersion() bool {
	if o != nil && !IsNil(o.ProcessDefinitionVersion) {
		return true
	}

	return false
}

// SetProcessDefinitionVersion gets a reference to the given IntegerFilterProperty and assigns it to the ProcessDefinitionVersion field.
func (o *ProcessInstanceFilterFields) SetProcessDefinitionVersion(v IntegerFilterProperty) {
	o.ProcessDefinitionVersion = &v
}

// GetProcessDefinitionVersionTag returns the ProcessDefinitionVersionTag field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionVersionTag() StringFilterProperty {
	if o == nil || IsNil(o.ProcessDefinitionVersionTag) {
		var ret StringFilterProperty
		return ret
	}
	return *o.ProcessDefinitionVersionTag
}

// GetProcessDefinitionVersionTagOk returns a tuple with the ProcessDefinitionVersionTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionVersionTagOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessDefinitionVersionTag) {
		return nil, false
	}
	return o.ProcessDefinitionVersionTag, true
}

// HasProcessDefinitionVersionTag returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasProcessDefinitionVersionTag() bool {
	if o != nil && !IsNil(o.ProcessDefinitionVersionTag) {
		return true
	}

	return false
}

// SetProcessDefinitionVersionTag gets a reference to the given StringFilterProperty and assigns it to the ProcessDefinitionVersionTag field.
func (o *ProcessInstanceFilterFields) SetProcessDefinitionVersionTag(v StringFilterProperty) {
	o.ProcessDefinitionVersionTag = &v
}

// GetProcessDefinitionKey returns the ProcessDefinitionKey field value if set, zero value otherwise.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionKey() ProcessDefinitionKeyFilterProperty {
	if o == nil || IsNil(o.ProcessDefinitionKey) {
		var ret ProcessDefinitionKeyFilterProperty
		return ret
	}
	return *o.ProcessDefinitionKey
}

// GetProcessDefinitionKeyOk returns a tuple with the ProcessDefinitionKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceFilterFields) GetProcessDefinitionKeyOk() (*ProcessDefinitionKeyFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessDefinitionKey) {
		return nil, false
	}
	return o.ProcessDefinitionKey, true
}

// HasProcessDefinitionKey returns a boolean if a field has been set.
func (o *ProcessInstanceFilterFields) HasProcessDefinitionKey() bool {
	if o != nil && !IsNil(o.ProcessDefinitionKey) {
		return true
	}

	return false
}

// SetProcessDefinitionKey gets a reference to the given ProcessDefinitionKeyFilterProperty and assigns it to the ProcessDefinitionKey field.
func (o *ProcessInstanceFilterFields) SetProcessDefinitionKey(v ProcessDefinitionKeyFilterProperty) {
	o.ProcessDefinitionKey = &v
}

func (o ProcessInstanceFilterFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessInstanceFilterFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.HasIncident) {
		toSerialize["hasIncident"] = o.HasIncident
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	if !IsNil(o.ProcessInstanceKey) {
		toSerialize["processInstanceKey"] = o.ProcessInstanceKey
	}
	if !IsNil(o.ParentProcessInstanceKey) {
		toSerialize["parentProcessInstanceKey"] = o.ParentProcessInstanceKey
	}
	if !IsNil(o.ParentElementInstanceKey) {
		toSerialize["parentElementInstanceKey"] = o.ParentElementInstanceKey
	}
	if !IsNil(o.BatchOperationId) {
		toSerialize["batchOperationId"] = o.BatchOperationId
	}
	if !IsNil(o.BatchOperationKey) {
		toSerialize["batchOperationKey"] = o.BatchOperationKey
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.HasRetriesLeft) {
		toSerialize["hasRetriesLeft"] = o.HasRetriesLeft
	}
	if !IsNil(o.ElementInstanceState) {
		toSerialize["elementInstanceState"] = o.ElementInstanceState
	}
	if !IsNil(o.ElementId) {
		toSerialize["elementId"] = o.ElementId
	}
	if !IsNil(o.HasElementInstanceIncident) {
		toSerialize["hasElementInstanceIncident"] = o.HasElementInstanceIncident
	}
	if !IsNil(o.IncidentErrorHashCode) {
		toSerialize["incidentErrorHashCode"] = o.IncidentErrorHashCode
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.BusinessId) {
		toSerialize["businessId"] = o.BusinessId
	}
	if !IsNil(o.ProcessDefinitionId) {
		toSerialize["processDefinitionId"] = o.ProcessDefinitionId
	}
	if !IsNil(o.ProcessDefinitionName) {
		toSerialize["processDefinitionName"] = o.ProcessDefinitionName
	}
	if !IsNil(o.ProcessDefinitionVersion) {
		toSerialize["processDefinitionVersion"] = o.ProcessDefinitionVersion
	}
	if !IsNil(o.ProcessDefinitionVersionTag) {
		toSerialize["processDefinitionVersionTag"] = o.ProcessDefinitionVersionTag
	}
	if !IsNil(o.ProcessDefinitionKey) {
		toSerialize["processDefinitionKey"] = o.ProcessDefinitionKey
	}
	return toSerialize, nil
}

type NullableProcessInstanceFilterFields struct {
	value *ProcessInstanceFilterFields
	isSet bool
}

func (v NullableProcessInstanceFilterFields) Get() *ProcessInstanceFilterFields {
	return v.value
}

func (v *NullableProcessInstanceFilterFields) Set(val *ProcessInstanceFilterFields) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessInstanceFilterFields) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessInstanceFilterFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessInstanceFilterFields(val *ProcessInstanceFilterFields) *NullableProcessInstanceFilterFields {
	return &NullableProcessInstanceFilterFields{value: val, isSet: true}
}

func (v NullableProcessInstanceFilterFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessInstanceFilterFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
