/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ClusterTopologyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterTopologyResponse{}

// ClusterTopologyResponse The topology of the whole cluster, aggregated over all physical tenants.
type ClusterTopologyResponse struct {
	// The brokers that are part of this cluster, across all physical tenants.
	Brokers []ClusterBrokerInfo `json:"brokers"`
	// The cluster Id.
	ClusterId NullableString `json:"clusterId"`
	// The number of brokers in the cluster.
	ClusterSize int32 `json:"clusterSize"`
	// The version of the Orchestration Cluster Gateway.
	GatewayVersion NullableString `json:"gatewayVersion"`
	// The topology of each physical tenant of this cluster.
	PhysicalTenants []PhysicalTenantTopology `json:"physicalTenants"`
}

type _ClusterTopologyResponse ClusterTopologyResponse

// NewClusterTopologyResponse instantiates a new ClusterTopologyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterTopologyResponse(brokers []ClusterBrokerInfo, clusterId NullableString, clusterSize int32, gatewayVersion NullableString, physicalTenants []PhysicalTenantTopology) *ClusterTopologyResponse {
	this := ClusterTopologyResponse{}
	this.Brokers = brokers
	this.ClusterId = clusterId
	this.ClusterSize = clusterSize
	this.GatewayVersion = gatewayVersion
	this.PhysicalTenants = physicalTenants
	return &this
}

// NewClusterTopologyResponseWithDefaults instantiates a new ClusterTopologyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterTopologyResponseWithDefaults() *ClusterTopologyResponse {
	this := ClusterTopologyResponse{}
	return &this
}

// GetBrokers returns the Brokers field value
func (o *ClusterTopologyResponse) GetBrokers() []ClusterBrokerInfo {
	if o == nil {
		var ret []ClusterBrokerInfo
		return ret
	}

	return o.Brokers
}

// GetBrokersOk returns a tuple with the Brokers field value
// and a boolean to check if the value has been set.
func (o *ClusterTopologyResponse) GetBrokersOk() ([]ClusterBrokerInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Brokers, true
}

// SetBrokers sets field value
func (o *ClusterTopologyResponse) SetBrokers(v []ClusterBrokerInfo) {
	o.Brokers = v
}

// GetClusterId returns the ClusterId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ClusterTopologyResponse) GetClusterId() string {
	if o == nil || o.ClusterId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ClusterId.Get()
}

// GetClusterIdOk returns a tuple with the ClusterId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterTopologyResponse) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClusterId.Get(), o.ClusterId.IsSet()
}

// SetClusterId sets field value
func (o *ClusterTopologyResponse) SetClusterId(v string) {
	o.ClusterId.Set(&v)
}

// GetClusterSize returns the ClusterSize field value
func (o *ClusterTopologyResponse) GetClusterSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ClusterSize
}

// GetClusterSizeOk returns a tuple with the ClusterSize field value
// and a boolean to check if the value has been set.
func (o *ClusterTopologyResponse) GetClusterSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterSize, true
}

// SetClusterSize sets field value
func (o *ClusterTopologyResponse) SetClusterSize(v int32) {
	o.ClusterSize = v
}

// GetGatewayVersion returns the GatewayVersion field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ClusterTopologyResponse) GetGatewayVersion() string {
	if o == nil || o.GatewayVersion.Get() == nil {
		var ret string
		return ret
	}

	return *o.GatewayVersion.Get()
}

// GetGatewayVersionOk returns a tuple with the GatewayVersion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterTopologyResponse) GetGatewayVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GatewayVersion.Get(), o.GatewayVersion.IsSet()
}

// SetGatewayVersion sets field value
func (o *ClusterTopologyResponse) SetGatewayVersion(v string) {
	o.GatewayVersion.Set(&v)
}

// GetPhysicalTenants returns the PhysicalTenants field value
func (o *ClusterTopologyResponse) GetPhysicalTenants() []PhysicalTenantTopology {
	if o == nil {
		var ret []PhysicalTenantTopology
		return ret
	}

	return o.PhysicalTenants
}

// GetPhysicalTenantsOk returns a tuple with the PhysicalTenants field value
// and a boolean to check if the value has been set.
func (o *ClusterTopologyResponse) GetPhysicalTenantsOk() ([]PhysicalTenantTopology, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhysicalTenants, true
}

// SetPhysicalTenants sets field value
func (o *ClusterTopologyResponse) SetPhysicalTenants(v []PhysicalTenantTopology) {
	o.PhysicalTenants = v
}

func (o ClusterTopologyResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterTopologyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["brokers"] = o.Brokers
	toSerialize["clusterId"] = o.ClusterId.Get()
	toSerialize["clusterSize"] = o.ClusterSize
	toSerialize["gatewayVersion"] = o.GatewayVersion.Get()
	toSerialize["physicalTenants"] = o.PhysicalTenants
	return toSerialize, nil
}

func (o *ClusterTopologyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"brokers",
		"clusterId",
		"clusterSize",
		"gatewayVersion",
		"physicalTenants",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterTopologyResponse := _ClusterTopologyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterTopologyResponse)

	if err != nil {
		return err
	}

	*o = ClusterTopologyResponse(varClusterTopologyResponse)

	return err
}

type NullableClusterTopologyResponse struct {
	value *ClusterTopologyResponse
	isSet bool
}

func (v NullableClusterTopologyResponse) Get() *ClusterTopologyResponse {
	return v.value
}

func (v *NullableClusterTopologyResponse) Set(val *ClusterTopologyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterTopologyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterTopologyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterTopologyResponse(val *ClusterTopologyResponse) *NullableClusterTopologyResponse {
	return &NullableClusterTopologyResponse{value: val, isSet: true}
}

func (v NullableClusterTopologyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterTopologyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
