/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdvancedWaitStateElementTypeFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvancedWaitStateElementTypeFilter{}

// AdvancedWaitStateElementTypeFilter Advanced element type filter.
type AdvancedWaitStateElementTypeFilter struct {
	// Checks for equality with the provided value.
	Eq *WaitStateElementTypeEnum `json:"$eq,omitempty"`
	// Checks for inequality with the provided value.
	Neq *WaitStateElementTypeEnum `json:"$neq,omitempty"`
	// Checks if the current property exists.
	Exists *bool `json:"$exists,omitempty"`
	// Checks if the property matches any of the provided values.
	In []WaitStateElementTypeEnum `json:"$in,omitempty"`
	// Checks if the property matches the provided like value.  Supported wildcard characters are:  * `*`: matches zero, one, or multiple characters. * `?`: matches one, single character.  Wildcard characters can be escaped with backslash, for instance: `\\*`.
	Like *string `json:"$like,omitempty"`
}

// NewAdvancedWaitStateElementTypeFilter instantiates a new AdvancedWaitStateElementTypeFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvancedWaitStateElementTypeFilter() *AdvancedWaitStateElementTypeFilter {
	this := AdvancedWaitStateElementTypeFilter{}
	return &this
}

// NewAdvancedWaitStateElementTypeFilterWithDefaults instantiates a new AdvancedWaitStateElementTypeFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvancedWaitStateElementTypeFilterWithDefaults() *AdvancedWaitStateElementTypeFilter {
	this := AdvancedWaitStateElementTypeFilter{}
	return &this
}

// GetEq returns the Eq field value if set, zero value otherwise.
func (o *AdvancedWaitStateElementTypeFilter) GetEq() WaitStateElementTypeEnum {
	if o == nil || IsNil(o.Eq) {
		var ret WaitStateElementTypeEnum
		return ret
	}
	return *o.Eq
}

// GetEqOk returns a tuple with the Eq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedWaitStateElementTypeFilter) GetEqOk() (*WaitStateElementTypeEnum, bool) {
	if o == nil || IsNil(o.Eq) {
		return nil, false
	}
	return o.Eq, true
}

// HasEq returns a boolean if a field has been set.
func (o *AdvancedWaitStateElementTypeFilter) HasEq() bool {
	if o != nil && !IsNil(o.Eq) {
		return true
	}

	return false
}

// SetEq gets a reference to the given WaitStateElementTypeEnum and assigns it to the Eq field.
func (o *AdvancedWaitStateElementTypeFilter) SetEq(v WaitStateElementTypeEnum) {
	o.Eq = &v
}

// GetNeq returns the Neq field value if set, zero value otherwise.
func (o *AdvancedWaitStateElementTypeFilter) GetNeq() WaitStateElementTypeEnum {
	if o == nil || IsNil(o.Neq) {
		var ret WaitStateElementTypeEnum
		return ret
	}
	return *o.Neq
}

// GetNeqOk returns a tuple with the Neq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedWaitStateElementTypeFilter) GetNeqOk() (*WaitStateElementTypeEnum, bool) {
	if o == nil || IsNil(o.Neq) {
		return nil, false
	}
	return o.Neq, true
}

// HasNeq returns a boolean if a field has been set.
func (o *AdvancedWaitStateElementTypeFilter) HasNeq() bool {
	if o != nil && !IsNil(o.Neq) {
		return true
	}

	return false
}

// SetNeq gets a reference to the given WaitStateElementTypeEnum and assigns it to the Neq field.
func (o *AdvancedWaitStateElementTypeFilter) SetNeq(v WaitStateElementTypeEnum) {
	o.Neq = &v
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *AdvancedWaitStateElementTypeFilter) GetExists() bool {
	if o == nil || IsNil(o.Exists) {
		var ret bool
		return ret
	}
	return *o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedWaitStateElementTypeFilter) GetExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.Exists) {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *AdvancedWaitStateElementTypeFilter) HasExists() bool {
	if o != nil && !IsNil(o.Exists) {
		return true
	}

	return false
}

// SetExists gets a reference to the given bool and assigns it to the Exists field.
func (o *AdvancedWaitStateElementTypeFilter) SetExists(v bool) {
	o.Exists = &v
}

// GetIn returns the In field value if set, zero value otherwise.
func (o *AdvancedWaitStateElementTypeFilter) GetIn() []WaitStateElementTypeEnum {
	if o == nil || IsNil(o.In) {
		var ret []WaitStateElementTypeEnum
		return ret
	}
	return o.In
}

// GetInOk returns a tuple with the In field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedWaitStateElementTypeFilter) GetInOk() ([]WaitStateElementTypeEnum, bool) {
	if o == nil || IsNil(o.In) {
		return nil, false
	}
	return o.In, true
}

// HasIn returns a boolean if a field has been set.
func (o *AdvancedWaitStateElementTypeFilter) HasIn() bool {
	if o != nil && !IsNil(o.In) {
		return true
	}

	return false
}

// SetIn gets a reference to the given []WaitStateElementTypeEnum and assigns it to the In field.
func (o *AdvancedWaitStateElementTypeFilter) SetIn(v []WaitStateElementTypeEnum) {
	o.In = v
}

// GetLike returns the Like field value if set, zero value otherwise.
func (o *AdvancedWaitStateElementTypeFilter) GetLike() string {
	if o == nil || IsNil(o.Like) {
		var ret string
		return ret
	}
	return *o.Like
}

// GetLikeOk returns a tuple with the Like field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedWaitStateElementTypeFilter) GetLikeOk() (*string, bool) {
	if o == nil || IsNil(o.Like) {
		return nil, false
	}
	return o.Like, true
}

// HasLike returns a boolean if a field has been set.
func (o *AdvancedWaitStateElementTypeFilter) HasLike() bool {
	if o != nil && !IsNil(o.Like) {
		return true
	}

	return false
}

// SetLike gets a reference to the given string and assigns it to the Like field.
func (o *AdvancedWaitStateElementTypeFilter) SetLike(v string) {
	o.Like = &v
}

func (o AdvancedWaitStateElementTypeFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvancedWaitStateElementTypeFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Eq) {
		toSerialize["$eq"] = o.Eq
	}
	if !IsNil(o.Neq) {
		toSerialize["$neq"] = o.Neq
	}
	if !IsNil(o.Exists) {
		toSerialize["$exists"] = o.Exists
	}
	if !IsNil(o.In) {
		toSerialize["$in"] = o.In
	}
	if !IsNil(o.Like) {
		toSerialize["$like"] = o.Like
	}
	return toSerialize, nil
}

type NullableAdvancedWaitStateElementTypeFilter struct {
	value *AdvancedWaitStateElementTypeFilter
	isSet bool
}

func (v NullableAdvancedWaitStateElementTypeFilter) Get() *AdvancedWaitStateElementTypeFilter {
	return v.value
}

func (v *NullableAdvancedWaitStateElementTypeFilter) Set(val *AdvancedWaitStateElementTypeFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvancedWaitStateElementTypeFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvancedWaitStateElementTypeFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvancedWaitStateElementTypeFilter(val *AdvancedWaitStateElementTypeFilter) *NullableAdvancedWaitStateElementTypeFilter {
	return &NullableAdvancedWaitStateElementTypeFilter{value: val, isSet: true}
}

func (v NullableAdvancedWaitStateElementTypeFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvancedWaitStateElementTypeFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
