/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UseSourceParentKeyInstruction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UseSourceParentKeyInstruction{}

// UseSourceParentKeyInstruction Instructs the engine to use the source's direct parent key as the ancestor scope key for the target element. This is a simpler alternative to `inferred` that skips hierarchy traversal and directly uses the source's parent key. This is useful when the source and target elements are siblings within the same flow scope.
type UseSourceParentKeyInstruction struct {
	// The type of ancestor scope instruction.
	AncestorScopeType string `json:"ancestorScopeType"`
}

type _UseSourceParentKeyInstruction UseSourceParentKeyInstruction

// NewUseSourceParentKeyInstruction instantiates a new UseSourceParentKeyInstruction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUseSourceParentKeyInstruction(ancestorScopeType string) *UseSourceParentKeyInstruction {
	this := UseSourceParentKeyInstruction{}
	this.AncestorScopeType = ancestorScopeType
	return &this
}

// NewUseSourceParentKeyInstructionWithDefaults instantiates a new UseSourceParentKeyInstruction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUseSourceParentKeyInstructionWithDefaults() *UseSourceParentKeyInstruction {
	this := UseSourceParentKeyInstruction{}
	return &this
}

// GetAncestorScopeType returns the AncestorScopeType field value
func (o *UseSourceParentKeyInstruction) GetAncestorScopeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AncestorScopeType
}

// GetAncestorScopeTypeOk returns a tuple with the AncestorScopeType field value
// and a boolean to check if the value has been set.
func (o *UseSourceParentKeyInstruction) GetAncestorScopeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AncestorScopeType, true
}

// SetAncestorScopeType sets field value
func (o *UseSourceParentKeyInstruction) SetAncestorScopeType(v string) {
	o.AncestorScopeType = v
}

func (o UseSourceParentKeyInstruction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UseSourceParentKeyInstruction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ancestorScopeType"] = o.AncestorScopeType
	return toSerialize, nil
}

func (o *UseSourceParentKeyInstruction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ancestorScopeType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUseSourceParentKeyInstruction := _UseSourceParentKeyInstruction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUseSourceParentKeyInstruction)

	if err != nil {
		return err
	}

	*o = UseSourceParentKeyInstruction(varUseSourceParentKeyInstruction)

	return err
}

type NullableUseSourceParentKeyInstruction struct {
	value *UseSourceParentKeyInstruction
	isSet bool
}

func (v NullableUseSourceParentKeyInstruction) Get() *UseSourceParentKeyInstruction {
	return v.value
}

func (v *NullableUseSourceParentKeyInstruction) Set(val *UseSourceParentKeyInstruction) {
	v.value = val
	v.isSet = true
}

func (v NullableUseSourceParentKeyInstruction) IsSet() bool {
	return v.isSet
}

func (v *NullableUseSourceParentKeyInstruction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUseSourceParentKeyInstruction(val *UseSourceParentKeyInstruction) *NullableUseSourceParentKeyInstruction {
	return &NullableUseSourceParentKeyInstruction{value: val, isSet: true}
}

func (v NullableUseSourceParentKeyInstruction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUseSourceParentKeyInstruction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
