/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AuthorizationIdBasedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizationIdBasedRequest{}

// AuthorizationIdBasedRequest struct for AuthorizationIdBasedRequest
type AuthorizationIdBasedRequest struct {
	// The ID of the owner of the permissions.
	OwnerId   string        `json:"ownerId"`
	OwnerType OwnerTypeEnum `json:"ownerType"`
	// The ID of the resource to add permissions to.
	ResourceId string `json:"resourceId"`
	// The type of resource to add permissions to.
	ResourceType ResourceTypeEnum `json:"resourceType"`
	// The permission types to add.
	PermissionTypes []PermissionTypeEnum `json:"permissionTypes"`
}

type _AuthorizationIdBasedRequest AuthorizationIdBasedRequest

// NewAuthorizationIdBasedRequest instantiates a new AuthorizationIdBasedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationIdBasedRequest(ownerId string, ownerType OwnerTypeEnum, resourceId string, resourceType ResourceTypeEnum, permissionTypes []PermissionTypeEnum) *AuthorizationIdBasedRequest {
	this := AuthorizationIdBasedRequest{}
	this.OwnerId = ownerId
	this.OwnerType = ownerType
	this.ResourceId = resourceId
	this.ResourceType = resourceType
	this.PermissionTypes = permissionTypes
	return &this
}

// NewAuthorizationIdBasedRequestWithDefaults instantiates a new AuthorizationIdBasedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationIdBasedRequestWithDefaults() *AuthorizationIdBasedRequest {
	this := AuthorizationIdBasedRequest{}
	return &this
}

// GetOwnerId returns the OwnerId field value
func (o *AuthorizationIdBasedRequest) GetOwnerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value
// and a boolean to check if the value has been set.
func (o *AuthorizationIdBasedRequest) GetOwnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerId, true
}

// SetOwnerId sets field value
func (o *AuthorizationIdBasedRequest) SetOwnerId(v string) {
	o.OwnerId = v
}

// GetOwnerType returns the OwnerType field value
func (o *AuthorizationIdBasedRequest) GetOwnerType() OwnerTypeEnum {
	if o == nil {
		var ret OwnerTypeEnum
		return ret
	}

	return o.OwnerType
}

// GetOwnerTypeOk returns a tuple with the OwnerType field value
// and a boolean to check if the value has been set.
func (o *AuthorizationIdBasedRequest) GetOwnerTypeOk() (*OwnerTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerType, true
}

// SetOwnerType sets field value
func (o *AuthorizationIdBasedRequest) SetOwnerType(v OwnerTypeEnum) {
	o.OwnerType = v
}

// GetResourceId returns the ResourceId field value
func (o *AuthorizationIdBasedRequest) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *AuthorizationIdBasedRequest) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *AuthorizationIdBasedRequest) SetResourceId(v string) {
	o.ResourceId = v
}

// GetResourceType returns the ResourceType field value
func (o *AuthorizationIdBasedRequest) GetResourceType() ResourceTypeEnum {
	if o == nil {
		var ret ResourceTypeEnum
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *AuthorizationIdBasedRequest) GetResourceTypeOk() (*ResourceTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *AuthorizationIdBasedRequest) SetResourceType(v ResourceTypeEnum) {
	o.ResourceType = v
}

// GetPermissionTypes returns the PermissionTypes field value
func (o *AuthorizationIdBasedRequest) GetPermissionTypes() []PermissionTypeEnum {
	if o == nil {
		var ret []PermissionTypeEnum
		return ret
	}

	return o.PermissionTypes
}

// GetPermissionTypesOk returns a tuple with the PermissionTypes field value
// and a boolean to check if the value has been set.
func (o *AuthorizationIdBasedRequest) GetPermissionTypesOk() ([]PermissionTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.PermissionTypes, true
}

// SetPermissionTypes sets field value
func (o *AuthorizationIdBasedRequest) SetPermissionTypes(v []PermissionTypeEnum) {
	o.PermissionTypes = v
}

func (o AuthorizationIdBasedRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizationIdBasedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ownerId"] = o.OwnerId
	toSerialize["ownerType"] = o.OwnerType
	toSerialize["resourceId"] = o.ResourceId
	toSerialize["resourceType"] = o.ResourceType
	toSerialize["permissionTypes"] = o.PermissionTypes
	return toSerialize, nil
}

func (o *AuthorizationIdBasedRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ownerId",
		"ownerType",
		"resourceId",
		"resourceType",
		"permissionTypes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorizationIdBasedRequest := _AuthorizationIdBasedRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorizationIdBasedRequest)

	if err != nil {
		return err
	}

	*o = AuthorizationIdBasedRequest(varAuthorizationIdBasedRequest)

	return err
}

type NullableAuthorizationIdBasedRequest struct {
	value *AuthorizationIdBasedRequest
	isSet bool
}

func (v NullableAuthorizationIdBasedRequest) Get() *AuthorizationIdBasedRequest {
	return v.value
}

func (v *NullableAuthorizationIdBasedRequest) Set(val *AuthorizationIdBasedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationIdBasedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationIdBasedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationIdBasedRequest(val *AuthorizationIdBasedRequest) *NullableAuthorizationIdBasedRequest {
	return &NullableAuthorizationIdBasedRequest{value: val, isSet: true}
}

func (v NullableAuthorizationIdBasedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationIdBasedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
