/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// AgentInstanceMessageContentTypeEnum The content type discriminator for a history item content block.
type AgentInstanceMessageContentTypeEnum string

// List of AgentInstanceMessageContentTypeEnum
const (
	AGENTINSTANCEMESSAGECONTENTTYPEENUM_TEXT     AgentInstanceMessageContentTypeEnum = "TEXT"
	AGENTINSTANCEMESSAGECONTENTTYPEENUM_DOCUMENT AgentInstanceMessageContentTypeEnum = "DOCUMENT"
	AGENTINSTANCEMESSAGECONTENTTYPEENUM_OBJECT   AgentInstanceMessageContentTypeEnum = "OBJECT"
)

// All allowed values of AgentInstanceMessageContentTypeEnum enum
var AllowedAgentInstanceMessageContentTypeEnumEnumValues = []AgentInstanceMessageContentTypeEnum{
	"TEXT",
	"DOCUMENT",
	"OBJECT",
}

func (v *AgentInstanceMessageContentTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AgentInstanceMessageContentTypeEnum(value)
	for _, existing := range AllowedAgentInstanceMessageContentTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AgentInstanceMessageContentTypeEnum", value)
}

// NewAgentInstanceMessageContentTypeEnumFromValue returns a pointer to a valid AgentInstanceMessageContentTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAgentInstanceMessageContentTypeEnumFromValue(v string) (*AgentInstanceMessageContentTypeEnum, error) {
	ev := AgentInstanceMessageContentTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AgentInstanceMessageContentTypeEnum: valid values are %v", v, AllowedAgentInstanceMessageContentTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AgentInstanceMessageContentTypeEnum) IsValid() bool {
	for _, existing := range AllowedAgentInstanceMessageContentTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AgentInstanceMessageContentTypeEnum value
func (v AgentInstanceMessageContentTypeEnum) Ptr() *AgentInstanceMessageContentTypeEnum {
	return &v
}

type NullableAgentInstanceMessageContentTypeEnum struct {
	value *AgentInstanceMessageContentTypeEnum
	isSet bool
}

func (v NullableAgentInstanceMessageContentTypeEnum) Get() *AgentInstanceMessageContentTypeEnum {
	return v.value
}

func (v *NullableAgentInstanceMessageContentTypeEnum) Set(val *AgentInstanceMessageContentTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentInstanceMessageContentTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentInstanceMessageContentTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentInstanceMessageContentTypeEnum(val *AgentInstanceMessageContentTypeEnum) *NullableAgentInstanceMessageContentTypeEnum {
	return &NullableAgentInstanceMessageContentTypeEnum{value: val, isSet: true}
}

func (v NullableAgentInstanceMessageContentTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentInstanceMessageContentTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
