/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RoleGroupSearchQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleGroupSearchQueryRequest{}

// RoleGroupSearchQueryRequest struct for RoleGroupSearchQueryRequest
type RoleGroupSearchQueryRequest struct {
	// Pagination criteria.
	Page *SearchQueryPageRequest `json:"page,omitempty"`
	// Sort field criteria.
	Sort []RoleGroupSearchQuerySortRequest `json:"sort,omitempty"`
}

// NewRoleGroupSearchQueryRequest instantiates a new RoleGroupSearchQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleGroupSearchQueryRequest() *RoleGroupSearchQueryRequest {
	this := RoleGroupSearchQueryRequest{}
	return &this
}

// NewRoleGroupSearchQueryRequestWithDefaults instantiates a new RoleGroupSearchQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleGroupSearchQueryRequestWithDefaults() *RoleGroupSearchQueryRequest {
	this := RoleGroupSearchQueryRequest{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *RoleGroupSearchQueryRequest) GetPage() SearchQueryPageRequest {
	if o == nil || IsNil(o.Page) {
		var ret SearchQueryPageRequest
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleGroupSearchQueryRequest) GetPageOk() (*SearchQueryPageRequest, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *RoleGroupSearchQueryRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given SearchQueryPageRequest and assigns it to the Page field.
func (o *RoleGroupSearchQueryRequest) SetPage(v SearchQueryPageRequest) {
	o.Page = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *RoleGroupSearchQueryRequest) GetSort() []RoleGroupSearchQuerySortRequest {
	if o == nil || IsNil(o.Sort) {
		var ret []RoleGroupSearchQuerySortRequest
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleGroupSearchQueryRequest) GetSortOk() ([]RoleGroupSearchQuerySortRequest, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *RoleGroupSearchQueryRequest) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []RoleGroupSearchQuerySortRequest and assigns it to the Sort field.
func (o *RoleGroupSearchQueryRequest) SetSort(v []RoleGroupSearchQuerySortRequest) {
	o.Sort = v
}

func (o RoleGroupSearchQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleGroupSearchQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	return toSerialize, nil
}

type NullableRoleGroupSearchQueryRequest struct {
	value *RoleGroupSearchQueryRequest
	isSet bool
}

func (v NullableRoleGroupSearchQueryRequest) Get() *RoleGroupSearchQueryRequest {
	return v.value
}

func (v *NullableRoleGroupSearchQueryRequest) Set(val *RoleGroupSearchQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleGroupSearchQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleGroupSearchQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleGroupSearchQueryRequest(val *RoleGroupSearchQueryRequest) *NullableRoleGroupSearchQueryRequest {
	return &NullableRoleGroupSearchQueryRequest{value: val, isSet: true}
}

func (v NullableRoleGroupSearchQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleGroupSearchQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
