/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdvancedAgentInstanceKeyFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvancedAgentInstanceKeyFilter{}

// AdvancedAgentInstanceKeyFilter Advanced AgentInstanceKey filter.
type AdvancedAgentInstanceKeyFilter struct {
	// Checks for equality with the provided value.
	Eq *ModelString `json:"$eq,omitempty"`
	// Checks for inequality with the provided value.
	Neq *ModelString `json:"$neq,omitempty"`
	// Checks if the current property exists.
	Exists *bool `json:"$exists,omitempty"`
	// Checks if the property matches any of the provided values.
	In []ModelString `json:"$in,omitempty"`
	// Checks if the property matches none of the provided values.
	NotIn []ModelString `json:"$notIn,omitempty"`
}

// NewAdvancedAgentInstanceKeyFilter instantiates a new AdvancedAgentInstanceKeyFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvancedAgentInstanceKeyFilter() *AdvancedAgentInstanceKeyFilter {
	this := AdvancedAgentInstanceKeyFilter{}
	return &this
}

// NewAdvancedAgentInstanceKeyFilterWithDefaults instantiates a new AdvancedAgentInstanceKeyFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvancedAgentInstanceKeyFilterWithDefaults() *AdvancedAgentInstanceKeyFilter {
	this := AdvancedAgentInstanceKeyFilter{}
	return &this
}

// GetEq returns the Eq field value if set, zero value otherwise.
func (o *AdvancedAgentInstanceKeyFilter) GetEq() ModelString {
	if o == nil || IsNil(o.Eq) {
		var ret ModelString
		return ret
	}
	return *o.Eq
}

// GetEqOk returns a tuple with the Eq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedAgentInstanceKeyFilter) GetEqOk() (*ModelString, bool) {
	if o == nil || IsNil(o.Eq) {
		return nil, false
	}
	return o.Eq, true
}

// HasEq returns a boolean if a field has been set.
func (o *AdvancedAgentInstanceKeyFilter) HasEq() bool {
	if o != nil && !IsNil(o.Eq) {
		return true
	}

	return false
}

// SetEq gets a reference to the given ModelString and assigns it to the Eq field.
func (o *AdvancedAgentInstanceKeyFilter) SetEq(v ModelString) {
	o.Eq = &v
}

// GetNeq returns the Neq field value if set, zero value otherwise.
func (o *AdvancedAgentInstanceKeyFilter) GetNeq() ModelString {
	if o == nil || IsNil(o.Neq) {
		var ret ModelString
		return ret
	}
	return *o.Neq
}

// GetNeqOk returns a tuple with the Neq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedAgentInstanceKeyFilter) GetNeqOk() (*ModelString, bool) {
	if o == nil || IsNil(o.Neq) {
		return nil, false
	}
	return o.Neq, true
}

// HasNeq returns a boolean if a field has been set.
func (o *AdvancedAgentInstanceKeyFilter) HasNeq() bool {
	if o != nil && !IsNil(o.Neq) {
		return true
	}

	return false
}

// SetNeq gets a reference to the given ModelString and assigns it to the Neq field.
func (o *AdvancedAgentInstanceKeyFilter) SetNeq(v ModelString) {
	o.Neq = &v
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *AdvancedAgentInstanceKeyFilter) GetExists() bool {
	if o == nil || IsNil(o.Exists) {
		var ret bool
		return ret
	}
	return *o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedAgentInstanceKeyFilter) GetExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.Exists) {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *AdvancedAgentInstanceKeyFilter) HasExists() bool {
	if o != nil && !IsNil(o.Exists) {
		return true
	}

	return false
}

// SetExists gets a reference to the given bool and assigns it to the Exists field.
func (o *AdvancedAgentInstanceKeyFilter) SetExists(v bool) {
	o.Exists = &v
}

// GetIn returns the In field value if set, zero value otherwise.
func (o *AdvancedAgentInstanceKeyFilter) GetIn() []ModelString {
	if o == nil || IsNil(o.In) {
		var ret []ModelString
		return ret
	}
	return o.In
}

// GetInOk returns a tuple with the In field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedAgentInstanceKeyFilter) GetInOk() ([]ModelString, bool) {
	if o == nil || IsNil(o.In) {
		return nil, false
	}
	return o.In, true
}

// HasIn returns a boolean if a field has been set.
func (o *AdvancedAgentInstanceKeyFilter) HasIn() bool {
	if o != nil && !IsNil(o.In) {
		return true
	}

	return false
}

// SetIn gets a reference to the given []ModelString and assigns it to the In field.
func (o *AdvancedAgentInstanceKeyFilter) SetIn(v []ModelString) {
	o.In = v
}

// GetNotIn returns the NotIn field value if set, zero value otherwise.
func (o *AdvancedAgentInstanceKeyFilter) GetNotIn() []ModelString {
	if o == nil || IsNil(o.NotIn) {
		var ret []ModelString
		return ret
	}
	return o.NotIn
}

// GetNotInOk returns a tuple with the NotIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedAgentInstanceKeyFilter) GetNotInOk() ([]ModelString, bool) {
	if o == nil || IsNil(o.NotIn) {
		return nil, false
	}
	return o.NotIn, true
}

// HasNotIn returns a boolean if a field has been set.
func (o *AdvancedAgentInstanceKeyFilter) HasNotIn() bool {
	if o != nil && !IsNil(o.NotIn) {
		return true
	}

	return false
}

// SetNotIn gets a reference to the given []ModelString and assigns it to the NotIn field.
func (o *AdvancedAgentInstanceKeyFilter) SetNotIn(v []ModelString) {
	o.NotIn = v
}

func (o AdvancedAgentInstanceKeyFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvancedAgentInstanceKeyFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Eq) {
		toSerialize["$eq"] = o.Eq
	}
	if !IsNil(o.Neq) {
		toSerialize["$neq"] = o.Neq
	}
	if !IsNil(o.Exists) {
		toSerialize["$exists"] = o.Exists
	}
	if !IsNil(o.In) {
		toSerialize["$in"] = o.In
	}
	if !IsNil(o.NotIn) {
		toSerialize["$notIn"] = o.NotIn
	}
	return toSerialize, nil
}

type NullableAdvancedAgentInstanceKeyFilter struct {
	value *AdvancedAgentInstanceKeyFilter
	isSet bool
}

func (v NullableAdvancedAgentInstanceKeyFilter) Get() *AdvancedAgentInstanceKeyFilter {
	return v.value
}

func (v *NullableAdvancedAgentInstanceKeyFilter) Set(val *AdvancedAgentInstanceKeyFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvancedAgentInstanceKeyFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvancedAgentInstanceKeyFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvancedAgentInstanceKeyFilter(val *AdvancedAgentInstanceKeyFilter) *NullableAdvancedAgentInstanceKeyFilter {
	return &NullableAdvancedAgentInstanceKeyFilter{value: val, isSet: true}
}

func (v NullableAdvancedAgentInstanceKeyFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvancedAgentInstanceKeyFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
