/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ClusterHistoryBackupInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterHistoryBackupInfo{}

// ClusterHistoryBackupInfo A history backup id and what each physical tenant reports for it. No cluster-level state is aggregated from the per-tenant states.
type ClusterHistoryBackupInfo struct {
	// The id of the backup.
	BackupId int64 `json:"backupId"`
	// What each physical tenant reports for this backup id, ordered by physical tenant id. When looking a backup id up directly, every targeted tenant is listed, including the ones reporting `NOT_FOUND`. Within a listing, only the tenants that hold the id are listed.
	PhysicalTenants []ClusterHistoryBackupTenantInfo `json:"physicalTenants"`
}

type _ClusterHistoryBackupInfo ClusterHistoryBackupInfo

// NewClusterHistoryBackupInfo instantiates a new ClusterHistoryBackupInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterHistoryBackupInfo(backupId int64, physicalTenants []ClusterHistoryBackupTenantInfo) *ClusterHistoryBackupInfo {
	this := ClusterHistoryBackupInfo{}
	this.BackupId = backupId
	this.PhysicalTenants = physicalTenants
	return &this
}

// NewClusterHistoryBackupInfoWithDefaults instantiates a new ClusterHistoryBackupInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterHistoryBackupInfoWithDefaults() *ClusterHistoryBackupInfo {
	this := ClusterHistoryBackupInfo{}
	return &this
}

// GetBackupId returns the BackupId field value
func (o *ClusterHistoryBackupInfo) GetBackupId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BackupId
}

// GetBackupIdOk returns a tuple with the BackupId field value
// and a boolean to check if the value has been set.
func (o *ClusterHistoryBackupInfo) GetBackupIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackupId, true
}

// SetBackupId sets field value
func (o *ClusterHistoryBackupInfo) SetBackupId(v int64) {
	o.BackupId = v
}

// GetPhysicalTenants returns the PhysicalTenants field value
func (o *ClusterHistoryBackupInfo) GetPhysicalTenants() []ClusterHistoryBackupTenantInfo {
	if o == nil {
		var ret []ClusterHistoryBackupTenantInfo
		return ret
	}

	return o.PhysicalTenants
}

// GetPhysicalTenantsOk returns a tuple with the PhysicalTenants field value
// and a boolean to check if the value has been set.
func (o *ClusterHistoryBackupInfo) GetPhysicalTenantsOk() ([]ClusterHistoryBackupTenantInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhysicalTenants, true
}

// SetPhysicalTenants sets field value
func (o *ClusterHistoryBackupInfo) SetPhysicalTenants(v []ClusterHistoryBackupTenantInfo) {
	o.PhysicalTenants = v
}

func (o ClusterHistoryBackupInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterHistoryBackupInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backupId"] = o.BackupId
	toSerialize["physicalTenants"] = o.PhysicalTenants
	return toSerialize, nil
}

func (o *ClusterHistoryBackupInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backupId",
		"physicalTenants",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterHistoryBackupInfo := _ClusterHistoryBackupInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterHistoryBackupInfo)

	if err != nil {
		return err
	}

	*o = ClusterHistoryBackupInfo(varClusterHistoryBackupInfo)

	return err
}

type NullableClusterHistoryBackupInfo struct {
	value *ClusterHistoryBackupInfo
	isSet bool
}

func (v NullableClusterHistoryBackupInfo) Get() *ClusterHistoryBackupInfo {
	return v.value
}

func (v *NullableClusterHistoryBackupInfo) Set(val *ClusterHistoryBackupInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterHistoryBackupInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterHistoryBackupInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterHistoryBackupInfo(val *ClusterHistoryBackupInfo) *NullableClusterHistoryBackupInfo {
	return &NullableClusterHistoryBackupInfo{value: val, isSet: true}
}

func (v NullableClusterHistoryBackupInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterHistoryBackupInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
