/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EvaluatedDecisionOutputItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EvaluatedDecisionOutputItem{}

// EvaluatedDecisionOutputItem The evaluated decision outputs.
type EvaluatedDecisionOutputItem struct {
	// The ID of the evaluated decison output item.
	OutputId string `json:"outputId"`
	// The name of the of the evaluated decison output item.
	OutputName string `json:"outputName"`
	// The value of the evaluated decison output item.
	OutputValue string `json:"outputValue"`
	// The ID of the matched rule.
	RuleId NullableString `json:"ruleId"`
	// The index of the matched rule.
	RuleIndex NullableInt32 `json:"ruleIndex"`
}

type _EvaluatedDecisionOutputItem EvaluatedDecisionOutputItem

// NewEvaluatedDecisionOutputItem instantiates a new EvaluatedDecisionOutputItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvaluatedDecisionOutputItem(outputId string, outputName string, outputValue string, ruleId NullableString, ruleIndex NullableInt32) *EvaluatedDecisionOutputItem {
	this := EvaluatedDecisionOutputItem{}
	this.OutputId = outputId
	this.OutputName = outputName
	this.OutputValue = outputValue
	this.RuleId = ruleId
	this.RuleIndex = ruleIndex
	return &this
}

// NewEvaluatedDecisionOutputItemWithDefaults instantiates a new EvaluatedDecisionOutputItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvaluatedDecisionOutputItemWithDefaults() *EvaluatedDecisionOutputItem {
	this := EvaluatedDecisionOutputItem{}
	return &this
}

// GetOutputId returns the OutputId field value
func (o *EvaluatedDecisionOutputItem) GetOutputId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutputId
}

// GetOutputIdOk returns a tuple with the OutputId field value
// and a boolean to check if the value has been set.
func (o *EvaluatedDecisionOutputItem) GetOutputIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutputId, true
}

// SetOutputId sets field value
func (o *EvaluatedDecisionOutputItem) SetOutputId(v string) {
	o.OutputId = v
}

// GetOutputName returns the OutputName field value
func (o *EvaluatedDecisionOutputItem) GetOutputName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutputName
}

// GetOutputNameOk returns a tuple with the OutputName field value
// and a boolean to check if the value has been set.
func (o *EvaluatedDecisionOutputItem) GetOutputNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutputName, true
}

// SetOutputName sets field value
func (o *EvaluatedDecisionOutputItem) SetOutputName(v string) {
	o.OutputName = v
}

// GetOutputValue returns the OutputValue field value
func (o *EvaluatedDecisionOutputItem) GetOutputValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutputValue
}

// GetOutputValueOk returns a tuple with the OutputValue field value
// and a boolean to check if the value has been set.
func (o *EvaluatedDecisionOutputItem) GetOutputValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutputValue, true
}

// SetOutputValue sets field value
func (o *EvaluatedDecisionOutputItem) SetOutputValue(v string) {
	o.OutputValue = v
}

// GetRuleId returns the RuleId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EvaluatedDecisionOutputItem) GetRuleId() string {
	if o == nil || o.RuleId.Get() == nil {
		var ret string
		return ret
	}

	return *o.RuleId.Get()
}

// GetRuleIdOk returns a tuple with the RuleId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EvaluatedDecisionOutputItem) GetRuleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RuleId.Get(), o.RuleId.IsSet()
}

// SetRuleId sets field value
func (o *EvaluatedDecisionOutputItem) SetRuleId(v string) {
	o.RuleId.Set(&v)
}

// GetRuleIndex returns the RuleIndex field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *EvaluatedDecisionOutputItem) GetRuleIndex() int32 {
	if o == nil || o.RuleIndex.Get() == nil {
		var ret int32
		return ret
	}

	return *o.RuleIndex.Get()
}

// GetRuleIndexOk returns a tuple with the RuleIndex field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EvaluatedDecisionOutputItem) GetRuleIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RuleIndex.Get(), o.RuleIndex.IsSet()
}

// SetRuleIndex sets field value
func (o *EvaluatedDecisionOutputItem) SetRuleIndex(v int32) {
	o.RuleIndex.Set(&v)
}

func (o EvaluatedDecisionOutputItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EvaluatedDecisionOutputItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["outputId"] = o.OutputId
	toSerialize["outputName"] = o.OutputName
	toSerialize["outputValue"] = o.OutputValue
	toSerialize["ruleId"] = o.RuleId.Get()
	toSerialize["ruleIndex"] = o.RuleIndex.Get()
	return toSerialize, nil
}

func (o *EvaluatedDecisionOutputItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"outputId",
		"outputName",
		"outputValue",
		"ruleId",
		"ruleIndex",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEvaluatedDecisionOutputItem := _EvaluatedDecisionOutputItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEvaluatedDecisionOutputItem)

	if err != nil {
		return err
	}

	*o = EvaluatedDecisionOutputItem(varEvaluatedDecisionOutputItem)

	return err
}

type NullableEvaluatedDecisionOutputItem struct {
	value *EvaluatedDecisionOutputItem
	isSet bool
}

func (v NullableEvaluatedDecisionOutputItem) Get() *EvaluatedDecisionOutputItem {
	return v.value
}

func (v *NullableEvaluatedDecisionOutputItem) Set(val *EvaluatedDecisionOutputItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEvaluatedDecisionOutputItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEvaluatedDecisionOutputItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvaluatedDecisionOutputItem(val *EvaluatedDecisionOutputItem) *NullableEvaluatedDecisionOutputItem {
	return &NullableEvaluatedDecisionOutputItem{value: val, isSet: true}
}

func (v NullableEvaluatedDecisionOutputItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvaluatedDecisionOutputItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
