/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdvancedElementIdFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvancedElementIdFilter{}

// AdvancedElementIdFilter Advanced ElementId filter.
type AdvancedElementIdFilter struct {
	// Checks for equality with the provided value.
	Eq *string `json:"$eq,omitempty"`
	// Checks for inequality with the provided value.
	Neq *string `json:"$neq,omitempty"`
	// Checks if the current property exists.
	Exists *bool `json:"$exists,omitempty"`
	// Checks if the property matches any of the provided values.
	In []string `json:"$in,omitempty"`
	// Checks if the property matches none of the provided values.
	NotIn []string `json:"$notIn,omitempty"`
	// Checks if the property matches the provided like value.  Supported wildcard characters are:  * `*`: matches zero, one, or multiple characters. * `?`: matches one, single character.  Wildcard characters can be escaped with backslash, for instance: `\\*`.
	Like *string `json:"$like,omitempty"`
}

// NewAdvancedElementIdFilter instantiates a new AdvancedElementIdFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvancedElementIdFilter() *AdvancedElementIdFilter {
	this := AdvancedElementIdFilter{}
	return &this
}

// NewAdvancedElementIdFilterWithDefaults instantiates a new AdvancedElementIdFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvancedElementIdFilterWithDefaults() *AdvancedElementIdFilter {
	this := AdvancedElementIdFilter{}
	return &this
}

// GetEq returns the Eq field value if set, zero value otherwise.
func (o *AdvancedElementIdFilter) GetEq() string {
	if o == nil || IsNil(o.Eq) {
		var ret string
		return ret
	}
	return *o.Eq
}

// GetEqOk returns a tuple with the Eq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedElementIdFilter) GetEqOk() (*string, bool) {
	if o == nil || IsNil(o.Eq) {
		return nil, false
	}
	return o.Eq, true
}

// HasEq returns a boolean if a field has been set.
func (o *AdvancedElementIdFilter) HasEq() bool {
	if o != nil && !IsNil(o.Eq) {
		return true
	}

	return false
}

// SetEq gets a reference to the given string and assigns it to the Eq field.
func (o *AdvancedElementIdFilter) SetEq(v string) {
	o.Eq = &v
}

// GetNeq returns the Neq field value if set, zero value otherwise.
func (o *AdvancedElementIdFilter) GetNeq() string {
	if o == nil || IsNil(o.Neq) {
		var ret string
		return ret
	}
	return *o.Neq
}

// GetNeqOk returns a tuple with the Neq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedElementIdFilter) GetNeqOk() (*string, bool) {
	if o == nil || IsNil(o.Neq) {
		return nil, false
	}
	return o.Neq, true
}

// HasNeq returns a boolean if a field has been set.
func (o *AdvancedElementIdFilter) HasNeq() bool {
	if o != nil && !IsNil(o.Neq) {
		return true
	}

	return false
}

// SetNeq gets a reference to the given string and assigns it to the Neq field.
func (o *AdvancedElementIdFilter) SetNeq(v string) {
	o.Neq = &v
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *AdvancedElementIdFilter) GetExists() bool {
	if o == nil || IsNil(o.Exists) {
		var ret bool
		return ret
	}
	return *o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedElementIdFilter) GetExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.Exists) {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *AdvancedElementIdFilter) HasExists() bool {
	if o != nil && !IsNil(o.Exists) {
		return true
	}

	return false
}

// SetExists gets a reference to the given bool and assigns it to the Exists field.
func (o *AdvancedElementIdFilter) SetExists(v bool) {
	o.Exists = &v
}

// GetIn returns the In field value if set, zero value otherwise.
func (o *AdvancedElementIdFilter) GetIn() []string {
	if o == nil || IsNil(o.In) {
		var ret []string
		return ret
	}
	return o.In
}

// GetInOk returns a tuple with the In field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedElementIdFilter) GetInOk() ([]string, bool) {
	if o == nil || IsNil(o.In) {
		return nil, false
	}
	return o.In, true
}

// HasIn returns a boolean if a field has been set.
func (o *AdvancedElementIdFilter) HasIn() bool {
	if o != nil && !IsNil(o.In) {
		return true
	}

	return false
}

// SetIn gets a reference to the given []string and assigns it to the In field.
func (o *AdvancedElementIdFilter) SetIn(v []string) {
	o.In = v
}

// GetNotIn returns the NotIn field value if set, zero value otherwise.
func (o *AdvancedElementIdFilter) GetNotIn() []string {
	if o == nil || IsNil(o.NotIn) {
		var ret []string
		return ret
	}
	return o.NotIn
}

// GetNotInOk returns a tuple with the NotIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedElementIdFilter) GetNotInOk() ([]string, bool) {
	if o == nil || IsNil(o.NotIn) {
		return nil, false
	}
	return o.NotIn, true
}

// HasNotIn returns a boolean if a field has been set.
func (o *AdvancedElementIdFilter) HasNotIn() bool {
	if o != nil && !IsNil(o.NotIn) {
		return true
	}

	return false
}

// SetNotIn gets a reference to the given []string and assigns it to the NotIn field.
func (o *AdvancedElementIdFilter) SetNotIn(v []string) {
	o.NotIn = v
}

// GetLike returns the Like field value if set, zero value otherwise.
func (o *AdvancedElementIdFilter) GetLike() string {
	if o == nil || IsNil(o.Like) {
		var ret string
		return ret
	}
	return *o.Like
}

// GetLikeOk returns a tuple with the Like field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedElementIdFilter) GetLikeOk() (*string, bool) {
	if o == nil || IsNil(o.Like) {
		return nil, false
	}
	return o.Like, true
}

// HasLike returns a boolean if a field has been set.
func (o *AdvancedElementIdFilter) HasLike() bool {
	if o != nil && !IsNil(o.Like) {
		return true
	}

	return false
}

// SetLike gets a reference to the given string and assigns it to the Like field.
func (o *AdvancedElementIdFilter) SetLike(v string) {
	o.Like = &v
}

func (o AdvancedElementIdFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvancedElementIdFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Eq) {
		toSerialize["$eq"] = o.Eq
	}
	if !IsNil(o.Neq) {
		toSerialize["$neq"] = o.Neq
	}
	if !IsNil(o.Exists) {
		toSerialize["$exists"] = o.Exists
	}
	if !IsNil(o.In) {
		toSerialize["$in"] = o.In
	}
	if !IsNil(o.NotIn) {
		toSerialize["$notIn"] = o.NotIn
	}
	if !IsNil(o.Like) {
		toSerialize["$like"] = o.Like
	}
	return toSerialize, nil
}

type NullableAdvancedElementIdFilter struct {
	value *AdvancedElementIdFilter
	isSet bool
}

func (v NullableAdvancedElementIdFilter) Get() *AdvancedElementIdFilter {
	return v.value
}

func (v *NullableAdvancedElementIdFilter) Set(val *AdvancedElementIdFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvancedElementIdFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvancedElementIdFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvancedElementIdFilter(val *AdvancedElementIdFilter) *NullableAdvancedElementIdFilter {
	return &NullableAdvancedElementIdFilter{value: val, isSet: true}
}

func (v NullableAdvancedElementIdFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvancedElementIdFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
