/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// IncidentStateFilterProperty - IncidentStateEnum with full advanced search capabilities.
type IncidentStateFilterProperty struct {
	AdvancedIncidentStateFilter *AdvancedIncidentStateFilter
	IncidentStateExactMatch     *IncidentStateExactMatch
}

// AdvancedIncidentStateFilterAsIncidentStateFilterProperty is a convenience function that returns AdvancedIncidentStateFilter wrapped in IncidentStateFilterProperty
func AdvancedIncidentStateFilterAsIncidentStateFilterProperty(v *AdvancedIncidentStateFilter) IncidentStateFilterProperty {
	return IncidentStateFilterProperty{
		AdvancedIncidentStateFilter: v,
	}
}

// IncidentStateExactMatchAsIncidentStateFilterProperty is a convenience function that returns IncidentStateExactMatch wrapped in IncidentStateFilterProperty
func IncidentStateExactMatchAsIncidentStateFilterProperty(v *IncidentStateExactMatch) IncidentStateFilterProperty {
	return IncidentStateFilterProperty{
		IncidentStateExactMatch: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *IncidentStateFilterProperty) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AdvancedIncidentStateFilter
	err = json.Unmarshal(data, &dst.AdvancedIncidentStateFilter)
	if err == nil {
		jsonAdvancedIncidentStateFilter, _ := json.Marshal(dst.AdvancedIncidentStateFilter)
		if string(jsonAdvancedIncidentStateFilter) == "{}" { // empty struct
			dst.AdvancedIncidentStateFilter = nil
		} else {
			match++
		}
	} else {
		dst.AdvancedIncidentStateFilter = nil
	}

	// try to unmarshal data into IncidentStateExactMatch
	err = json.Unmarshal(data, &dst.IncidentStateExactMatch)
	if err == nil {
		jsonIncidentStateExactMatch, _ := json.Marshal(dst.IncidentStateExactMatch)
		if string(jsonIncidentStateExactMatch) == "{}" { // empty struct
			dst.IncidentStateExactMatch = nil
		} else {
			match++
		}
	} else {
		dst.IncidentStateExactMatch = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AdvancedIncidentStateFilter = nil
		dst.IncidentStateExactMatch = nil

		return fmt.Errorf("data matches more than one schema in oneOf(IncidentStateFilterProperty)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(IncidentStateFilterProperty)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src IncidentStateFilterProperty) MarshalJSON() ([]byte, error) {
	if src.AdvancedIncidentStateFilter != nil {
		return json.Marshal(&src.AdvancedIncidentStateFilter)
	}

	if src.IncidentStateExactMatch != nil {
		return json.Marshal(&src.IncidentStateExactMatch)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *IncidentStateFilterProperty) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.AdvancedIncidentStateFilter != nil {
		return obj.AdvancedIncidentStateFilter
	}

	if obj.IncidentStateExactMatch != nil {
		return obj.IncidentStateExactMatch
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj IncidentStateFilterProperty) GetActualInstanceValue() interface{} {
	if obj.AdvancedIncidentStateFilter != nil {
		return *obj.AdvancedIncidentStateFilter
	}

	if obj.IncidentStateExactMatch != nil {
		return *obj.IncidentStateExactMatch
	}

	// all schemas are nil
	return nil
}

type NullableIncidentStateFilterProperty struct {
	value *IncidentStateFilterProperty
	isSet bool
}

func (v NullableIncidentStateFilterProperty) Get() *IncidentStateFilterProperty {
	return v.value
}

func (v *NullableIncidentStateFilterProperty) Set(val *IncidentStateFilterProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentStateFilterProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentStateFilterProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentStateFilterProperty(val *IncidentStateFilterProperty) *NullableIncidentStateFilterProperty {
	return &NullableIncidentStateFilterProperty{value: val, isSet: true}
}

func (v NullableIncidentStateFilterProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentStateFilterProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
