/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// BatchOperationItemStateFilterProperty - BatchOperationItemStateEnum property with full advanced search capabilities.
type BatchOperationItemStateFilterProperty struct {
	AdvancedBatchOperationItemStateFilter *AdvancedBatchOperationItemStateFilter
	BatchOperationItemStateExactMatch     *BatchOperationItemStateExactMatch
}

// AdvancedBatchOperationItemStateFilterAsBatchOperationItemStateFilterProperty is a convenience function that returns AdvancedBatchOperationItemStateFilter wrapped in BatchOperationItemStateFilterProperty
func AdvancedBatchOperationItemStateFilterAsBatchOperationItemStateFilterProperty(v *AdvancedBatchOperationItemStateFilter) BatchOperationItemStateFilterProperty {
	return BatchOperationItemStateFilterProperty{
		AdvancedBatchOperationItemStateFilter: v,
	}
}

// BatchOperationItemStateExactMatchAsBatchOperationItemStateFilterProperty is a convenience function that returns BatchOperationItemStateExactMatch wrapped in BatchOperationItemStateFilterProperty
func BatchOperationItemStateExactMatchAsBatchOperationItemStateFilterProperty(v *BatchOperationItemStateExactMatch) BatchOperationItemStateFilterProperty {
	return BatchOperationItemStateFilterProperty{
		BatchOperationItemStateExactMatch: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BatchOperationItemStateFilterProperty) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AdvancedBatchOperationItemStateFilter
	err = json.Unmarshal(data, &dst.AdvancedBatchOperationItemStateFilter)
	if err == nil {
		jsonAdvancedBatchOperationItemStateFilter, _ := json.Marshal(dst.AdvancedBatchOperationItemStateFilter)
		if string(jsonAdvancedBatchOperationItemStateFilter) == "{}" { // empty struct
			dst.AdvancedBatchOperationItemStateFilter = nil
		} else {
			match++
		}
	} else {
		dst.AdvancedBatchOperationItemStateFilter = nil
	}

	// try to unmarshal data into BatchOperationItemStateExactMatch
	err = json.Unmarshal(data, &dst.BatchOperationItemStateExactMatch)
	if err == nil {
		jsonBatchOperationItemStateExactMatch, _ := json.Marshal(dst.BatchOperationItemStateExactMatch)
		if string(jsonBatchOperationItemStateExactMatch) == "{}" { // empty struct
			dst.BatchOperationItemStateExactMatch = nil
		} else {
			match++
		}
	} else {
		dst.BatchOperationItemStateExactMatch = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AdvancedBatchOperationItemStateFilter = nil
		dst.BatchOperationItemStateExactMatch = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BatchOperationItemStateFilterProperty)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(BatchOperationItemStateFilterProperty)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BatchOperationItemStateFilterProperty) MarshalJSON() ([]byte, error) {
	if src.AdvancedBatchOperationItemStateFilter != nil {
		return json.Marshal(&src.AdvancedBatchOperationItemStateFilter)
	}

	if src.BatchOperationItemStateExactMatch != nil {
		return json.Marshal(&src.BatchOperationItemStateExactMatch)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BatchOperationItemStateFilterProperty) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.AdvancedBatchOperationItemStateFilter != nil {
		return obj.AdvancedBatchOperationItemStateFilter
	}

	if obj.BatchOperationItemStateExactMatch != nil {
		return obj.BatchOperationItemStateExactMatch
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BatchOperationItemStateFilterProperty) GetActualInstanceValue() interface{} {
	if obj.AdvancedBatchOperationItemStateFilter != nil {
		return *obj.AdvancedBatchOperationItemStateFilter
	}

	if obj.BatchOperationItemStateExactMatch != nil {
		return *obj.BatchOperationItemStateExactMatch
	}

	// all schemas are nil
	return nil
}

type NullableBatchOperationItemStateFilterProperty struct {
	value *BatchOperationItemStateFilterProperty
	isSet bool
}

func (v NullableBatchOperationItemStateFilterProperty) Get() *BatchOperationItemStateFilterProperty {
	return v.value
}

func (v *NullableBatchOperationItemStateFilterProperty) Set(val *BatchOperationItemStateFilterProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchOperationItemStateFilterProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchOperationItemStateFilterProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchOperationItemStateFilterProperty(val *BatchOperationItemStateFilterProperty) *NullableBatchOperationItemStateFilterProperty {
	return &NullableBatchOperationItemStateFilterProperty{value: val, isSet: true}
}

func (v NullableBatchOperationItemStateFilterProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchOperationItemStateFilterProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
