/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DecisionInstanceSearchQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DecisionInstanceSearchQuery{}

// DecisionInstanceSearchQuery struct for DecisionInstanceSearchQuery
type DecisionInstanceSearchQuery struct {
	// Pagination criteria.
	Page *SearchQueryPageRequest `json:"page,omitempty"`
	// Sort field criteria.
	Sort []DecisionInstanceSearchQuerySortRequest `json:"sort,omitempty"`
	// The decision instance search filters.
	Filter *DecisionInstanceFilter `json:"filter,omitempty"`
}

// NewDecisionInstanceSearchQuery instantiates a new DecisionInstanceSearchQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecisionInstanceSearchQuery() *DecisionInstanceSearchQuery {
	this := DecisionInstanceSearchQuery{}
	return &this
}

// NewDecisionInstanceSearchQueryWithDefaults instantiates a new DecisionInstanceSearchQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecisionInstanceSearchQueryWithDefaults() *DecisionInstanceSearchQuery {
	this := DecisionInstanceSearchQuery{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *DecisionInstanceSearchQuery) GetPage() SearchQueryPageRequest {
	if o == nil || IsNil(o.Page) {
		var ret SearchQueryPageRequest
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionInstanceSearchQuery) GetPageOk() (*SearchQueryPageRequest, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *DecisionInstanceSearchQuery) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given SearchQueryPageRequest and assigns it to the Page field.
func (o *DecisionInstanceSearchQuery) SetPage(v SearchQueryPageRequest) {
	o.Page = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *DecisionInstanceSearchQuery) GetSort() []DecisionInstanceSearchQuerySortRequest {
	if o == nil || IsNil(o.Sort) {
		var ret []DecisionInstanceSearchQuerySortRequest
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionInstanceSearchQuery) GetSortOk() ([]DecisionInstanceSearchQuerySortRequest, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *DecisionInstanceSearchQuery) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []DecisionInstanceSearchQuerySortRequest and assigns it to the Sort field.
func (o *DecisionInstanceSearchQuery) SetSort(v []DecisionInstanceSearchQuerySortRequest) {
	o.Sort = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *DecisionInstanceSearchQuery) GetFilter() DecisionInstanceFilter {
	if o == nil || IsNil(o.Filter) {
		var ret DecisionInstanceFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionInstanceSearchQuery) GetFilterOk() (*DecisionInstanceFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *DecisionInstanceSearchQuery) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given DecisionInstanceFilter and assigns it to the Filter field.
func (o *DecisionInstanceSearchQuery) SetFilter(v DecisionInstanceFilter) {
	o.Filter = &v
}

func (o DecisionInstanceSearchQuery) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DecisionInstanceSearchQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	return toSerialize, nil
}

type NullableDecisionInstanceSearchQuery struct {
	value *DecisionInstanceSearchQuery
	isSet bool
}

func (v NullableDecisionInstanceSearchQuery) Get() *DecisionInstanceSearchQuery {
	return v.value
}

func (v *NullableDecisionInstanceSearchQuery) Set(val *DecisionInstanceSearchQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableDecisionInstanceSearchQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableDecisionInstanceSearchQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecisionInstanceSearchQuery(val *DecisionInstanceSearchQuery) *NullableDecisionInstanceSearchQuery {
	return &NullableDecisionInstanceSearchQuery{value: val, isSet: true}
}

func (v NullableDecisionInstanceSearchQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecisionInstanceSearchQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
