/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// UserTaskStateFilterProperty - UserTaskStateEnum property with full advanced search capabilities.
type UserTaskStateFilterProperty struct {
	AdvancedUserTaskStateFilter *AdvancedUserTaskStateFilter
	UserTaskStateExactMatch     *UserTaskStateExactMatch
}

// AdvancedUserTaskStateFilterAsUserTaskStateFilterProperty is a convenience function that returns AdvancedUserTaskStateFilter wrapped in UserTaskStateFilterProperty
func AdvancedUserTaskStateFilterAsUserTaskStateFilterProperty(v *AdvancedUserTaskStateFilter) UserTaskStateFilterProperty {
	return UserTaskStateFilterProperty{
		AdvancedUserTaskStateFilter: v,
	}
}

// UserTaskStateExactMatchAsUserTaskStateFilterProperty is a convenience function that returns UserTaskStateExactMatch wrapped in UserTaskStateFilterProperty
func UserTaskStateExactMatchAsUserTaskStateFilterProperty(v *UserTaskStateExactMatch) UserTaskStateFilterProperty {
	return UserTaskStateFilterProperty{
		UserTaskStateExactMatch: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *UserTaskStateFilterProperty) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AdvancedUserTaskStateFilter
	err = json.Unmarshal(data, &dst.AdvancedUserTaskStateFilter)
	if err == nil {
		jsonAdvancedUserTaskStateFilter, _ := json.Marshal(dst.AdvancedUserTaskStateFilter)
		if string(jsonAdvancedUserTaskStateFilter) == "{}" { // empty struct
			dst.AdvancedUserTaskStateFilter = nil
		} else {
			match++
		}
	} else {
		dst.AdvancedUserTaskStateFilter = nil
	}

	// try to unmarshal data into UserTaskStateExactMatch
	err = json.Unmarshal(data, &dst.UserTaskStateExactMatch)
	if err == nil {
		jsonUserTaskStateExactMatch, _ := json.Marshal(dst.UserTaskStateExactMatch)
		if string(jsonUserTaskStateExactMatch) == "{}" { // empty struct
			dst.UserTaskStateExactMatch = nil
		} else {
			match++
		}
	} else {
		dst.UserTaskStateExactMatch = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AdvancedUserTaskStateFilter = nil
		dst.UserTaskStateExactMatch = nil

		return fmt.Errorf("data matches more than one schema in oneOf(UserTaskStateFilterProperty)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(UserTaskStateFilterProperty)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UserTaskStateFilterProperty) MarshalJSON() ([]byte, error) {
	if src.AdvancedUserTaskStateFilter != nil {
		return json.Marshal(&src.AdvancedUserTaskStateFilter)
	}

	if src.UserTaskStateExactMatch != nil {
		return json.Marshal(&src.UserTaskStateExactMatch)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UserTaskStateFilterProperty) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.AdvancedUserTaskStateFilter != nil {
		return obj.AdvancedUserTaskStateFilter
	}

	if obj.UserTaskStateExactMatch != nil {
		return obj.UserTaskStateExactMatch
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj UserTaskStateFilterProperty) GetActualInstanceValue() interface{} {
	if obj.AdvancedUserTaskStateFilter != nil {
		return *obj.AdvancedUserTaskStateFilter
	}

	if obj.UserTaskStateExactMatch != nil {
		return *obj.UserTaskStateExactMatch
	}

	// all schemas are nil
	return nil
}

type NullableUserTaskStateFilterProperty struct {
	value *UserTaskStateFilterProperty
	isSet bool
}

func (v NullableUserTaskStateFilterProperty) Get() *UserTaskStateFilterProperty {
	return v.value
}

func (v *NullableUserTaskStateFilterProperty) Set(val *UserTaskStateFilterProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTaskStateFilterProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTaskStateFilterProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTaskStateFilterProperty(val *UserTaskStateFilterProperty) *NullableUserTaskStateFilterProperty {
	return &NullableUserTaskStateFilterProperty{value: val, isSet: true}
}

func (v NullableUserTaskStateFilterProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTaskStateFilterProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
