/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserFilter{}

// UserFilter User search filter.
type UserFilter struct {
	// The username of the user.
	Username *StringFilterProperty `json:"username,omitempty"`
	// The name of the user.
	Name *StringFilterProperty `json:"name,omitempty"`
	// The email of the user.
	Email *StringFilterProperty `json:"email,omitempty"`
}

// NewUserFilter instantiates a new UserFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserFilter() *UserFilter {
	this := UserFilter{}
	return &this
}

// NewUserFilterWithDefaults instantiates a new UserFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserFilterWithDefaults() *UserFilter {
	this := UserFilter{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *UserFilter) GetUsername() StringFilterProperty {
	if o == nil || IsNil(o.Username) {
		var ret StringFilterProperty
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserFilter) GetUsernameOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *UserFilter) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given StringFilterProperty and assigns it to the Username field.
func (o *UserFilter) SetUsername(v StringFilterProperty) {
	o.Username = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UserFilter) GetName() StringFilterProperty {
	if o == nil || IsNil(o.Name) {
		var ret StringFilterProperty
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserFilter) GetNameOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UserFilter) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given StringFilterProperty and assigns it to the Name field.
func (o *UserFilter) SetName(v StringFilterProperty) {
	o.Name = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UserFilter) GetEmail() StringFilterProperty {
	if o == nil || IsNil(o.Email) {
		var ret StringFilterProperty
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserFilter) GetEmailOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserFilter) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given StringFilterProperty and assigns it to the Email field.
func (o *UserFilter) SetEmail(v StringFilterProperty) {
	o.Email = &v
}

func (o UserFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableUserFilter struct {
	value *UserFilter
	isSet bool
}

func (v NullableUserFilter) Get() *UserFilter {
	return v.value
}

func (v *NullableUserFilter) Set(val *UserFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableUserFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableUserFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserFilter(val *UserFilter) *NullableUserFilter {
	return &NullableUserFilter{value: val, isSet: true}
}

func (v NullableUserFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
