/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProcessInstanceIncidentResolutionBatchOperationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessInstanceIncidentResolutionBatchOperationRequest{}

// ProcessInstanceIncidentResolutionBatchOperationRequest The process instance filter that defines which process instances should have their incidents resolved.
type ProcessInstanceIncidentResolutionBatchOperationRequest struct {
	// The process instance filter.
	Filter ProcessInstanceFilter `json:"filter"`
	// A reference key chosen by the user that will be part of all records resulting from this operation. Must be > 0 if provided.
	OperationReference *int64 `json:"operationReference,omitempty"`
}

type _ProcessInstanceIncidentResolutionBatchOperationRequest ProcessInstanceIncidentResolutionBatchOperationRequest

// NewProcessInstanceIncidentResolutionBatchOperationRequest instantiates a new ProcessInstanceIncidentResolutionBatchOperationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessInstanceIncidentResolutionBatchOperationRequest(filter ProcessInstanceFilter) *ProcessInstanceIncidentResolutionBatchOperationRequest {
	this := ProcessInstanceIncidentResolutionBatchOperationRequest{}
	this.Filter = filter
	return &this
}

// NewProcessInstanceIncidentResolutionBatchOperationRequestWithDefaults instantiates a new ProcessInstanceIncidentResolutionBatchOperationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessInstanceIncidentResolutionBatchOperationRequestWithDefaults() *ProcessInstanceIncidentResolutionBatchOperationRequest {
	this := ProcessInstanceIncidentResolutionBatchOperationRequest{}
	return &this
}

// GetFilter returns the Filter field value
func (o *ProcessInstanceIncidentResolutionBatchOperationRequest) GetFilter() ProcessInstanceFilter {
	if o == nil {
		var ret ProcessInstanceFilter
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *ProcessInstanceIncidentResolutionBatchOperationRequest) GetFilterOk() (*ProcessInstanceFilter, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filter, true
}

// SetFilter sets field value
func (o *ProcessInstanceIncidentResolutionBatchOperationRequest) SetFilter(v ProcessInstanceFilter) {
	o.Filter = v
}

// GetOperationReference returns the OperationReference field value if set, zero value otherwise.
func (o *ProcessInstanceIncidentResolutionBatchOperationRequest) GetOperationReference() int64 {
	if o == nil || IsNil(o.OperationReference) {
		var ret int64
		return ret
	}
	return *o.OperationReference
}

// GetOperationReferenceOk returns a tuple with the OperationReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessInstanceIncidentResolutionBatchOperationRequest) GetOperationReferenceOk() (*int64, bool) {
	if o == nil || IsNil(o.OperationReference) {
		return nil, false
	}
	return o.OperationReference, true
}

// HasOperationReference returns a boolean if a field has been set.
func (o *ProcessInstanceIncidentResolutionBatchOperationRequest) HasOperationReference() bool {
	if o != nil && !IsNil(o.OperationReference) {
		return true
	}

	return false
}

// SetOperationReference gets a reference to the given int64 and assigns it to the OperationReference field.
func (o *ProcessInstanceIncidentResolutionBatchOperationRequest) SetOperationReference(v int64) {
	o.OperationReference = &v
}

func (o ProcessInstanceIncidentResolutionBatchOperationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessInstanceIncidentResolutionBatchOperationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filter"] = o.Filter
	if !IsNil(o.OperationReference) {
		toSerialize["operationReference"] = o.OperationReference
	}
	return toSerialize, nil
}

func (o *ProcessInstanceIncidentResolutionBatchOperationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filter",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProcessInstanceIncidentResolutionBatchOperationRequest := _ProcessInstanceIncidentResolutionBatchOperationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProcessInstanceIncidentResolutionBatchOperationRequest)

	if err != nil {
		return err
	}

	*o = ProcessInstanceIncidentResolutionBatchOperationRequest(varProcessInstanceIncidentResolutionBatchOperationRequest)

	return err
}

type NullableProcessInstanceIncidentResolutionBatchOperationRequest struct {
	value *ProcessInstanceIncidentResolutionBatchOperationRequest
	isSet bool
}

func (v NullableProcessInstanceIncidentResolutionBatchOperationRequest) Get() *ProcessInstanceIncidentResolutionBatchOperationRequest {
	return v.value
}

func (v *NullableProcessInstanceIncidentResolutionBatchOperationRequest) Set(val *ProcessInstanceIncidentResolutionBatchOperationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessInstanceIncidentResolutionBatchOperationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessInstanceIncidentResolutionBatchOperationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessInstanceIncidentResolutionBatchOperationRequest(val *ProcessInstanceIncidentResolutionBatchOperationRequest) *NullableProcessInstanceIncidentResolutionBatchOperationRequest {
	return &NullableProcessInstanceIncidentResolutionBatchOperationRequest{value: val, isSet: true}
}

func (v NullableProcessInstanceIncidentResolutionBatchOperationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessInstanceIncidentResolutionBatchOperationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
