/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PartitionBackupInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartitionBackupInfo{}

// PartitionBackupInfo Detailed info of the backup for a given partition.
type PartitionBackupInfo struct {
	// The id of the partition.
	PartitionId int32 `json:"partitionId"`
	// The state of the backup on this partition.
	State StateCode `json:"state"`
	// Failure reason if the state is 'FAILED'.
	FailureReason NullableString `json:"failureReason"`
	// The timestamp at which the backup was started on this partition.
	CreatedAt NullableTime `json:"createdAt"`
	// The timestamp at which the backup was last updated on this partition, e.g. changed state from 'IN_PROGRESS' to 'COMPLETED'.
	LastUpdatedAt NullableTime `json:"lastUpdatedAt"`
	// The id of the snapshot which is included in this backup.
	SnapshotId NullableString `json:"snapshotId"`
	// The first log position included in this backup.
	FirstLogPosition NullableInt64 `json:"firstLogPosition"`
	// The position of the checkpoint for this backup.
	CheckpointPosition NullableInt64 `json:"checkpointPosition"`
	// The id of the broker from which the backup was taken for this partition.
	BrokerId NullableInt32 `json:"brokerId"`
	// The version of the broker from which the backup was taken for this partition.
	BrokerVersion NullableString `json:"brokerVersion"`
}

type _PartitionBackupInfo PartitionBackupInfo

// NewPartitionBackupInfo instantiates a new PartitionBackupInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartitionBackupInfo(partitionId int32, state StateCode, failureReason NullableString, createdAt NullableTime, lastUpdatedAt NullableTime, snapshotId NullableString, firstLogPosition NullableInt64, checkpointPosition NullableInt64, brokerId NullableInt32, brokerVersion NullableString) *PartitionBackupInfo {
	this := PartitionBackupInfo{}
	this.PartitionId = partitionId
	this.State = state
	this.FailureReason = failureReason
	this.CreatedAt = createdAt
	this.LastUpdatedAt = lastUpdatedAt
	this.SnapshotId = snapshotId
	this.FirstLogPosition = firstLogPosition
	this.CheckpointPosition = checkpointPosition
	this.BrokerId = brokerId
	this.BrokerVersion = brokerVersion
	return &this
}

// NewPartitionBackupInfoWithDefaults instantiates a new PartitionBackupInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartitionBackupInfoWithDefaults() *PartitionBackupInfo {
	this := PartitionBackupInfo{}
	return &this
}

// GetPartitionId returns the PartitionId field value
func (o *PartitionBackupInfo) GetPartitionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PartitionId
}

// GetPartitionIdOk returns a tuple with the PartitionId field value
// and a boolean to check if the value has been set.
func (o *PartitionBackupInfo) GetPartitionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartitionId, true
}

// SetPartitionId sets field value
func (o *PartitionBackupInfo) SetPartitionId(v int32) {
	o.PartitionId = v
}

// GetState returns the State field value
func (o *PartitionBackupInfo) GetState() StateCode {
	if o == nil {
		var ret StateCode
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *PartitionBackupInfo) GetStateOk() (*StateCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *PartitionBackupInfo) SetState(v StateCode) {
	o.State = v
}

// GetFailureReason returns the FailureReason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PartitionBackupInfo) GetFailureReason() string {
	if o == nil || o.FailureReason.Get() == nil {
		var ret string
		return ret
	}

	return *o.FailureReason.Get()
}

// GetFailureReasonOk returns a tuple with the FailureReason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartitionBackupInfo) GetFailureReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailureReason.Get(), o.FailureReason.IsSet()
}

// SetFailureReason sets field value
func (o *PartitionBackupInfo) SetFailureReason(v string) {
	o.FailureReason.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *PartitionBackupInfo) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartitionBackupInfo) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// SetCreatedAt sets field value
func (o *PartitionBackupInfo) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// GetLastUpdatedAt returns the LastUpdatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *PartitionBackupInfo) GetLastUpdatedAt() time.Time {
	if o == nil || o.LastUpdatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastUpdatedAt.Get()
}

// GetLastUpdatedAtOk returns a tuple with the LastUpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartitionBackupInfo) GetLastUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedAt.Get(), o.LastUpdatedAt.IsSet()
}

// SetLastUpdatedAt sets field value
func (o *PartitionBackupInfo) SetLastUpdatedAt(v time.Time) {
	o.LastUpdatedAt.Set(&v)
}

// GetSnapshotId returns the SnapshotId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PartitionBackupInfo) GetSnapshotId() string {
	if o == nil || o.SnapshotId.Get() == nil {
		var ret string
		return ret
	}

	return *o.SnapshotId.Get()
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartitionBackupInfo) GetSnapshotIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnapshotId.Get(), o.SnapshotId.IsSet()
}

// SetSnapshotId sets field value
func (o *PartitionBackupInfo) SetSnapshotId(v string) {
	o.SnapshotId.Set(&v)
}

// GetFirstLogPosition returns the FirstLogPosition field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *PartitionBackupInfo) GetFirstLogPosition() int64 {
	if o == nil || o.FirstLogPosition.Get() == nil {
		var ret int64
		return ret
	}

	return *o.FirstLogPosition.Get()
}

// GetFirstLogPositionOk returns a tuple with the FirstLogPosition field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartitionBackupInfo) GetFirstLogPositionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstLogPosition.Get(), o.FirstLogPosition.IsSet()
}

// SetFirstLogPosition sets field value
func (o *PartitionBackupInfo) SetFirstLogPosition(v int64) {
	o.FirstLogPosition.Set(&v)
}

// GetCheckpointPosition returns the CheckpointPosition field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *PartitionBackupInfo) GetCheckpointPosition() int64 {
	if o == nil || o.CheckpointPosition.Get() == nil {
		var ret int64
		return ret
	}

	return *o.CheckpointPosition.Get()
}

// GetCheckpointPositionOk returns a tuple with the CheckpointPosition field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartitionBackupInfo) GetCheckpointPositionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.CheckpointPosition.Get(), o.CheckpointPosition.IsSet()
}

// SetCheckpointPosition sets field value
func (o *PartitionBackupInfo) SetCheckpointPosition(v int64) {
	o.CheckpointPosition.Set(&v)
}

// GetBrokerId returns the BrokerId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *PartitionBackupInfo) GetBrokerId() int32 {
	if o == nil || o.BrokerId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.BrokerId.Get()
}

// GetBrokerIdOk returns a tuple with the BrokerId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartitionBackupInfo) GetBrokerIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrokerId.Get(), o.BrokerId.IsSet()
}

// SetBrokerId sets field value
func (o *PartitionBackupInfo) SetBrokerId(v int32) {
	o.BrokerId.Set(&v)
}

// GetBrokerVersion returns the BrokerVersion field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PartitionBackupInfo) GetBrokerVersion() string {
	if o == nil || o.BrokerVersion.Get() == nil {
		var ret string
		return ret
	}

	return *o.BrokerVersion.Get()
}

// GetBrokerVersionOk returns a tuple with the BrokerVersion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartitionBackupInfo) GetBrokerVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrokerVersion.Get(), o.BrokerVersion.IsSet()
}

// SetBrokerVersion sets field value
func (o *PartitionBackupInfo) SetBrokerVersion(v string) {
	o.BrokerVersion.Set(&v)
}

func (o PartitionBackupInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartitionBackupInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["partitionId"] = o.PartitionId
	toSerialize["state"] = o.State
	toSerialize["failureReason"] = o.FailureReason.Get()
	toSerialize["createdAt"] = o.CreatedAt.Get()
	toSerialize["lastUpdatedAt"] = o.LastUpdatedAt.Get()
	toSerialize["snapshotId"] = o.SnapshotId.Get()
	toSerialize["firstLogPosition"] = o.FirstLogPosition.Get()
	toSerialize["checkpointPosition"] = o.CheckpointPosition.Get()
	toSerialize["brokerId"] = o.BrokerId.Get()
	toSerialize["brokerVersion"] = o.BrokerVersion.Get()
	return toSerialize, nil
}

func (o *PartitionBackupInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"partitionId",
		"state",
		"failureReason",
		"createdAt",
		"lastUpdatedAt",
		"snapshotId",
		"firstLogPosition",
		"checkpointPosition",
		"brokerId",
		"brokerVersion",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartitionBackupInfo := _PartitionBackupInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartitionBackupInfo)

	if err != nil {
		return err
	}

	*o = PartitionBackupInfo(varPartitionBackupInfo)

	return err
}

type NullablePartitionBackupInfo struct {
	value *PartitionBackupInfo
	isSet bool
}

func (v NullablePartitionBackupInfo) Get() *PartitionBackupInfo {
	return v.value
}

func (v *NullablePartitionBackupInfo) Set(val *PartitionBackupInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePartitionBackupInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePartitionBackupInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartitionBackupInfo(val *PartitionBackupInfo) *NullablePartitionBackupInfo {
	return &NullablePartitionBackupInfo{value: val, isSet: true}
}

func (v NullablePartitionBackupInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartitionBackupInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
