/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BatchOperationItemStateExactMatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchOperationItemStateExactMatch{}

// BatchOperationItemStateExactMatch Matches the value exactly.
type BatchOperationItemStateExactMatch struct {
}

// NewBatchOperationItemStateExactMatch instantiates a new BatchOperationItemStateExactMatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchOperationItemStateExactMatch() *BatchOperationItemStateExactMatch {
	this := BatchOperationItemStateExactMatch{}
	return &this
}

// NewBatchOperationItemStateExactMatchWithDefaults instantiates a new BatchOperationItemStateExactMatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchOperationItemStateExactMatchWithDefaults() *BatchOperationItemStateExactMatch {
	this := BatchOperationItemStateExactMatch{}
	return &this
}

func (o BatchOperationItemStateExactMatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchOperationItemStateExactMatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableBatchOperationItemStateExactMatch struct {
	value *BatchOperationItemStateExactMatch
	isSet bool
}

func (v NullableBatchOperationItemStateExactMatch) Get() *BatchOperationItemStateExactMatch {
	return v.value
}

func (v *NullableBatchOperationItemStateExactMatch) Set(val *BatchOperationItemStateExactMatch) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchOperationItemStateExactMatch) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchOperationItemStateExactMatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchOperationItemStateExactMatch(val *BatchOperationItemStateExactMatch) *NullableBatchOperationItemStateExactMatch {
	return &NullableBatchOperationItemStateExactMatch{value: val, isSet: true}
}

func (v NullableBatchOperationItemStateExactMatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchOperationItemStateExactMatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
