/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RoleUserSearchQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleUserSearchQueryRequest{}

// RoleUserSearchQueryRequest struct for RoleUserSearchQueryRequest
type RoleUserSearchQueryRequest struct {
	// Pagination criteria.
	Page *SearchQueryPageRequest `json:"page,omitempty"`
	// Sort field criteria.
	Sort []RoleUserSearchQuerySortRequest `json:"sort,omitempty"`
}

// NewRoleUserSearchQueryRequest instantiates a new RoleUserSearchQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleUserSearchQueryRequest() *RoleUserSearchQueryRequest {
	this := RoleUserSearchQueryRequest{}
	return &this
}

// NewRoleUserSearchQueryRequestWithDefaults instantiates a new RoleUserSearchQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleUserSearchQueryRequestWithDefaults() *RoleUserSearchQueryRequest {
	this := RoleUserSearchQueryRequest{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *RoleUserSearchQueryRequest) GetPage() SearchQueryPageRequest {
	if o == nil || IsNil(o.Page) {
		var ret SearchQueryPageRequest
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleUserSearchQueryRequest) GetPageOk() (*SearchQueryPageRequest, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *RoleUserSearchQueryRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given SearchQueryPageRequest and assigns it to the Page field.
func (o *RoleUserSearchQueryRequest) SetPage(v SearchQueryPageRequest) {
	o.Page = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *RoleUserSearchQueryRequest) GetSort() []RoleUserSearchQuerySortRequest {
	if o == nil || IsNil(o.Sort) {
		var ret []RoleUserSearchQuerySortRequest
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleUserSearchQueryRequest) GetSortOk() ([]RoleUserSearchQuerySortRequest, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *RoleUserSearchQueryRequest) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []RoleUserSearchQuerySortRequest and assigns it to the Sort field.
func (o *RoleUserSearchQueryRequest) SetSort(v []RoleUserSearchQuerySortRequest) {
	o.Sort = v
}

func (o RoleUserSearchQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleUserSearchQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	return toSerialize, nil
}

type NullableRoleUserSearchQueryRequest struct {
	value *RoleUserSearchQueryRequest
	isSet bool
}

func (v NullableRoleUserSearchQueryRequest) Get() *RoleUserSearchQueryRequest {
	return v.value
}

func (v *NullableRoleUserSearchQueryRequest) Set(val *RoleUserSearchQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleUserSearchQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleUserSearchQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleUserSearchQueryRequest(val *RoleUserSearchQueryRequest) *NullableRoleUserSearchQueryRequest {
	return &NullableRoleUserSearchQueryRequest{value: val, isSet: true}
}

func (v NullableRoleUserSearchQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleUserSearchQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
