/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ClusterRebalanceOperationPartition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterRebalanceOperationPartition{}

// ClusterRebalanceOperationPartition One partition's plan, progress, and outcome within a rebalance.
type ClusterRebalanceOperationPartition struct {
	// The unique ID of this partition, within its physical tenant.
	PartitionId int32 `json:"partitionId"`
	// The partition group this partition belongs to.
	PhysicalTenantId string `json:"physicalTenantId"`
	// The leader last observed by this rebalance, or absent if there was no leader.
	CurrentLeader NullableString `json:"currentLeader"`
	// The leader selected when this rebalance was planned.
	DesiredLeader string `json:"desiredLeader"`
	// Where this rebalance has reached for the partition.
	Progress string `json:"progress"`
	// The terminal outcome, present only when progress is COMPLETED.
	Result NullableString `json:"result"`
}

type _ClusterRebalanceOperationPartition ClusterRebalanceOperationPartition

// NewClusterRebalanceOperationPartition instantiates a new ClusterRebalanceOperationPartition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterRebalanceOperationPartition(partitionId int32, physicalTenantId string, currentLeader NullableString, desiredLeader string, progress string, result NullableString) *ClusterRebalanceOperationPartition {
	this := ClusterRebalanceOperationPartition{}
	this.PartitionId = partitionId
	this.PhysicalTenantId = physicalTenantId
	this.CurrentLeader = currentLeader
	this.DesiredLeader = desiredLeader
	this.Progress = progress
	this.Result = result
	return &this
}

// NewClusterRebalanceOperationPartitionWithDefaults instantiates a new ClusterRebalanceOperationPartition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterRebalanceOperationPartitionWithDefaults() *ClusterRebalanceOperationPartition {
	this := ClusterRebalanceOperationPartition{}
	return &this
}

// GetPartitionId returns the PartitionId field value
func (o *ClusterRebalanceOperationPartition) GetPartitionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PartitionId
}

// GetPartitionIdOk returns a tuple with the PartitionId field value
// and a boolean to check if the value has been set.
func (o *ClusterRebalanceOperationPartition) GetPartitionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartitionId, true
}

// SetPartitionId sets field value
func (o *ClusterRebalanceOperationPartition) SetPartitionId(v int32) {
	o.PartitionId = v
}

// GetPhysicalTenantId returns the PhysicalTenantId field value
func (o *ClusterRebalanceOperationPartition) GetPhysicalTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhysicalTenantId
}

// GetPhysicalTenantIdOk returns a tuple with the PhysicalTenantId field value
// and a boolean to check if the value has been set.
func (o *ClusterRebalanceOperationPartition) GetPhysicalTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhysicalTenantId, true
}

// SetPhysicalTenantId sets field value
func (o *ClusterRebalanceOperationPartition) SetPhysicalTenantId(v string) {
	o.PhysicalTenantId = v
}

// GetCurrentLeader returns the CurrentLeader field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ClusterRebalanceOperationPartition) GetCurrentLeader() string {
	if o == nil || o.CurrentLeader.Get() == nil {
		var ret string
		return ret
	}

	return *o.CurrentLeader.Get()
}

// GetCurrentLeaderOk returns a tuple with the CurrentLeader field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterRebalanceOperationPartition) GetCurrentLeaderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentLeader.Get(), o.CurrentLeader.IsSet()
}

// SetCurrentLeader sets field value
func (o *ClusterRebalanceOperationPartition) SetCurrentLeader(v string) {
	o.CurrentLeader.Set(&v)
}

// GetDesiredLeader returns the DesiredLeader field value
func (o *ClusterRebalanceOperationPartition) GetDesiredLeader() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DesiredLeader
}

// GetDesiredLeaderOk returns a tuple with the DesiredLeader field value
// and a boolean to check if the value has been set.
func (o *ClusterRebalanceOperationPartition) GetDesiredLeaderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DesiredLeader, true
}

// SetDesiredLeader sets field value
func (o *ClusterRebalanceOperationPartition) SetDesiredLeader(v string) {
	o.DesiredLeader = v
}

// GetProgress returns the Progress field value
func (o *ClusterRebalanceOperationPartition) GetProgress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Progress
}

// GetProgressOk returns a tuple with the Progress field value
// and a boolean to check if the value has been set.
func (o *ClusterRebalanceOperationPartition) GetProgressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Progress, true
}

// SetProgress sets field value
func (o *ClusterRebalanceOperationPartition) SetProgress(v string) {
	o.Progress = v
}

// GetResult returns the Result field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ClusterRebalanceOperationPartition) GetResult() string {
	if o == nil || o.Result.Get() == nil {
		var ret string
		return ret
	}

	return *o.Result.Get()
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterRebalanceOperationPartition) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result.Get(), o.Result.IsSet()
}

// SetResult sets field value
func (o *ClusterRebalanceOperationPartition) SetResult(v string) {
	o.Result.Set(&v)
}

func (o ClusterRebalanceOperationPartition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterRebalanceOperationPartition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["partitionId"] = o.PartitionId
	toSerialize["physicalTenantId"] = o.PhysicalTenantId
	toSerialize["currentLeader"] = o.CurrentLeader.Get()
	toSerialize["desiredLeader"] = o.DesiredLeader
	toSerialize["progress"] = o.Progress
	toSerialize["result"] = o.Result.Get()
	return toSerialize, nil
}

func (o *ClusterRebalanceOperationPartition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"partitionId",
		"physicalTenantId",
		"currentLeader",
		"desiredLeader",
		"progress",
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterRebalanceOperationPartition := _ClusterRebalanceOperationPartition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterRebalanceOperationPartition)

	if err != nil {
		return err
	}

	*o = ClusterRebalanceOperationPartition(varClusterRebalanceOperationPartition)

	return err
}

type NullableClusterRebalanceOperationPartition struct {
	value *ClusterRebalanceOperationPartition
	isSet bool
}

func (v NullableClusterRebalanceOperationPartition) Get() *ClusterRebalanceOperationPartition {
	return v.value
}

func (v *NullableClusterRebalanceOperationPartition) Set(val *ClusterRebalanceOperationPartition) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterRebalanceOperationPartition) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterRebalanceOperationPartition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterRebalanceOperationPartition(val *ClusterRebalanceOperationPartition) *NullableClusterRebalanceOperationPartition {
	return &NullableClusterRebalanceOperationPartition{value: val, isSet: true}
}

func (v NullableClusterRebalanceOperationPartition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterRebalanceOperationPartition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
