/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GroupFilterFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupFilterFields{}

// GroupFilterFields Group filter request
type GroupFilterFields struct {
	// The group ID search filters.
	GroupId *StringFilterProperty `json:"groupId,omitempty"`
	// The group name search filters.
	Name *StringFilterProperty `json:"name,omitempty"`
}

// NewGroupFilterFields instantiates a new GroupFilterFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupFilterFields() *GroupFilterFields {
	this := GroupFilterFields{}
	return &this
}

// NewGroupFilterFieldsWithDefaults instantiates a new GroupFilterFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupFilterFieldsWithDefaults() *GroupFilterFields {
	this := GroupFilterFields{}
	return &this
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *GroupFilterFields) GetGroupId() StringFilterProperty {
	if o == nil || IsNil(o.GroupId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupFilterFields) GetGroupIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *GroupFilterFields) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given StringFilterProperty and assigns it to the GroupId field.
func (o *GroupFilterFields) SetGroupId(v StringFilterProperty) {
	o.GroupId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GroupFilterFields) GetName() StringFilterProperty {
	if o == nil || IsNil(o.Name) {
		var ret StringFilterProperty
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupFilterFields) GetNameOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GroupFilterFields) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given StringFilterProperty and assigns it to the Name field.
func (o *GroupFilterFields) SetName(v StringFilterProperty) {
	o.Name = &v
}

func (o GroupFilterFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupFilterFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupId) {
		toSerialize["groupId"] = o.GroupId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGroupFilterFields struct {
	value *GroupFilterFields
	isSet bool
}

func (v NullableGroupFilterFields) Get() *GroupFilterFields {
	return v.value
}

func (v *NullableGroupFilterFields) Set(val *GroupFilterFields) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupFilterFields) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupFilterFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupFilterFields(val *GroupFilterFields) *NullableGroupFilterFields {
	return &NullableGroupFilterFields{value: val, isSet: true}
}

func (v NullableGroupFilterFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupFilterFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
