/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdvancedBatchOperationTypeFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvancedBatchOperationTypeFilter{}

// AdvancedBatchOperationTypeFilter Advanced BatchOperationTypeEnum filter.
type AdvancedBatchOperationTypeFilter struct {
	// Checks for equality with the provided value.
	Eq *BatchOperationTypeEnum `json:"$eq,omitempty"`
	// Checks for inequality with the provided value.
	Neq *BatchOperationTypeEnum `json:"$neq,omitempty"`
	// Checks if the current property exists.
	Exists *bool `json:"$exists,omitempty"`
	// Checks if the property matches any of the provided values.
	In []BatchOperationTypeEnum `json:"$in,omitempty"`
	// Checks if the property matches the provided like value.  Supported wildcard characters are:  * `*`: matches zero, one, or multiple characters. * `?`: matches one, single character.  Wildcard characters can be escaped with backslash, for instance: `\\*`.
	Like *string `json:"$like,omitempty"`
}

// NewAdvancedBatchOperationTypeFilter instantiates a new AdvancedBatchOperationTypeFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvancedBatchOperationTypeFilter() *AdvancedBatchOperationTypeFilter {
	this := AdvancedBatchOperationTypeFilter{}
	return &this
}

// NewAdvancedBatchOperationTypeFilterWithDefaults instantiates a new AdvancedBatchOperationTypeFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvancedBatchOperationTypeFilterWithDefaults() *AdvancedBatchOperationTypeFilter {
	this := AdvancedBatchOperationTypeFilter{}
	return &this
}

// GetEq returns the Eq field value if set, zero value otherwise.
func (o *AdvancedBatchOperationTypeFilter) GetEq() BatchOperationTypeEnum {
	if o == nil || IsNil(o.Eq) {
		var ret BatchOperationTypeEnum
		return ret
	}
	return *o.Eq
}

// GetEqOk returns a tuple with the Eq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedBatchOperationTypeFilter) GetEqOk() (*BatchOperationTypeEnum, bool) {
	if o == nil || IsNil(o.Eq) {
		return nil, false
	}
	return o.Eq, true
}

// HasEq returns a boolean if a field has been set.
func (o *AdvancedBatchOperationTypeFilter) HasEq() bool {
	if o != nil && !IsNil(o.Eq) {
		return true
	}

	return false
}

// SetEq gets a reference to the given BatchOperationTypeEnum and assigns it to the Eq field.
func (o *AdvancedBatchOperationTypeFilter) SetEq(v BatchOperationTypeEnum) {
	o.Eq = &v
}

// GetNeq returns the Neq field value if set, zero value otherwise.
func (o *AdvancedBatchOperationTypeFilter) GetNeq() BatchOperationTypeEnum {
	if o == nil || IsNil(o.Neq) {
		var ret BatchOperationTypeEnum
		return ret
	}
	return *o.Neq
}

// GetNeqOk returns a tuple with the Neq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedBatchOperationTypeFilter) GetNeqOk() (*BatchOperationTypeEnum, bool) {
	if o == nil || IsNil(o.Neq) {
		return nil, false
	}
	return o.Neq, true
}

// HasNeq returns a boolean if a field has been set.
func (o *AdvancedBatchOperationTypeFilter) HasNeq() bool {
	if o != nil && !IsNil(o.Neq) {
		return true
	}

	return false
}

// SetNeq gets a reference to the given BatchOperationTypeEnum and assigns it to the Neq field.
func (o *AdvancedBatchOperationTypeFilter) SetNeq(v BatchOperationTypeEnum) {
	o.Neq = &v
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *AdvancedBatchOperationTypeFilter) GetExists() bool {
	if o == nil || IsNil(o.Exists) {
		var ret bool
		return ret
	}
	return *o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedBatchOperationTypeFilter) GetExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.Exists) {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *AdvancedBatchOperationTypeFilter) HasExists() bool {
	if o != nil && !IsNil(o.Exists) {
		return true
	}

	return false
}

// SetExists gets a reference to the given bool and assigns it to the Exists field.
func (o *AdvancedBatchOperationTypeFilter) SetExists(v bool) {
	o.Exists = &v
}

// GetIn returns the In field value if set, zero value otherwise.
func (o *AdvancedBatchOperationTypeFilter) GetIn() []BatchOperationTypeEnum {
	if o == nil || IsNil(o.In) {
		var ret []BatchOperationTypeEnum
		return ret
	}
	return o.In
}

// GetInOk returns a tuple with the In field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedBatchOperationTypeFilter) GetInOk() ([]BatchOperationTypeEnum, bool) {
	if o == nil || IsNil(o.In) {
		return nil, false
	}
	return o.In, true
}

// HasIn returns a boolean if a field has been set.
func (o *AdvancedBatchOperationTypeFilter) HasIn() bool {
	if o != nil && !IsNil(o.In) {
		return true
	}

	return false
}

// SetIn gets a reference to the given []BatchOperationTypeEnum and assigns it to the In field.
func (o *AdvancedBatchOperationTypeFilter) SetIn(v []BatchOperationTypeEnum) {
	o.In = v
}

// GetLike returns the Like field value if set, zero value otherwise.
func (o *AdvancedBatchOperationTypeFilter) GetLike() string {
	if o == nil || IsNil(o.Like) {
		var ret string
		return ret
	}
	return *o.Like
}

// GetLikeOk returns a tuple with the Like field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedBatchOperationTypeFilter) GetLikeOk() (*string, bool) {
	if o == nil || IsNil(o.Like) {
		return nil, false
	}
	return o.Like, true
}

// HasLike returns a boolean if a field has been set.
func (o *AdvancedBatchOperationTypeFilter) HasLike() bool {
	if o != nil && !IsNil(o.Like) {
		return true
	}

	return false
}

// SetLike gets a reference to the given string and assigns it to the Like field.
func (o *AdvancedBatchOperationTypeFilter) SetLike(v string) {
	o.Like = &v
}

func (o AdvancedBatchOperationTypeFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvancedBatchOperationTypeFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Eq) {
		toSerialize["$eq"] = o.Eq
	}
	if !IsNil(o.Neq) {
		toSerialize["$neq"] = o.Neq
	}
	if !IsNil(o.Exists) {
		toSerialize["$exists"] = o.Exists
	}
	if !IsNil(o.In) {
		toSerialize["$in"] = o.In
	}
	if !IsNil(o.Like) {
		toSerialize["$like"] = o.Like
	}
	return toSerialize, nil
}

type NullableAdvancedBatchOperationTypeFilter struct {
	value *AdvancedBatchOperationTypeFilter
	isSet bool
}

func (v NullableAdvancedBatchOperationTypeFilter) Get() *AdvancedBatchOperationTypeFilter {
	return v.value
}

func (v *NullableAdvancedBatchOperationTypeFilter) Set(val *AdvancedBatchOperationTypeFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvancedBatchOperationTypeFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvancedBatchOperationTypeFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvancedBatchOperationTypeFilter(val *AdvancedBatchOperationTypeFilter) *NullableAdvancedBatchOperationTypeFilter {
	return &NullableAdvancedBatchOperationTypeFilter{value: val, isSet: true}
}

func (v NullableAdvancedBatchOperationTypeFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvancedBatchOperationTypeFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
