/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HistoryBackupInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HistoryBackupInfo{}

// HistoryBackupInfo Detailed status of a history backup. The aggregated state is computed from the state of each of its snapshots as: - If every expected snapshot exists and all are complete, the overall state is   'COMPLETED'. - If one snapshot failed or is partial, the overall state is 'FAILED'. - Otherwise, if one snapshot is incompatible, the overall state is 'INCOMPATIBLE'. - Otherwise, if one snapshot is still running, the overall state is 'IN_PROGRESS'. - Otherwise, if snapshots are missing and the backup has not progressed within the   configured timeout, the overall state is 'INCOMPLETE'.
type HistoryBackupInfo struct {
	// The id of the backup.
	BackupId int64 `json:"backupId"`
	// The aggregated state of the backup.
	State HistoryBackupStateCode `json:"state"`
	// Reason for failure if the state is 'FAILED'.
	FailureReason NullableString `json:"failureReason"`
	// Detailed status of the backup per snapshot. Always lists every snapshot found for the backup; when the backup was read without snapshot detail, each entry carries only its name.
	Details []HistoryBackupSnapshotInfo `json:"details"`
}

type _HistoryBackupInfo HistoryBackupInfo

// NewHistoryBackupInfo instantiates a new HistoryBackupInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHistoryBackupInfo(backupId int64, state HistoryBackupStateCode, failureReason NullableString, details []HistoryBackupSnapshotInfo) *HistoryBackupInfo {
	this := HistoryBackupInfo{}
	this.BackupId = backupId
	this.State = state
	this.FailureReason = failureReason
	this.Details = details
	return &this
}

// NewHistoryBackupInfoWithDefaults instantiates a new HistoryBackupInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHistoryBackupInfoWithDefaults() *HistoryBackupInfo {
	this := HistoryBackupInfo{}
	return &this
}

// GetBackupId returns the BackupId field value
func (o *HistoryBackupInfo) GetBackupId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BackupId
}

// GetBackupIdOk returns a tuple with the BackupId field value
// and a boolean to check if the value has been set.
func (o *HistoryBackupInfo) GetBackupIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackupId, true
}

// SetBackupId sets field value
func (o *HistoryBackupInfo) SetBackupId(v int64) {
	o.BackupId = v
}

// GetState returns the State field value
func (o *HistoryBackupInfo) GetState() HistoryBackupStateCode {
	if o == nil {
		var ret HistoryBackupStateCode
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *HistoryBackupInfo) GetStateOk() (*HistoryBackupStateCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *HistoryBackupInfo) SetState(v HistoryBackupStateCode) {
	o.State = v
}

// GetFailureReason returns the FailureReason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *HistoryBackupInfo) GetFailureReason() string {
	if o == nil || o.FailureReason.Get() == nil {
		var ret string
		return ret
	}

	return *o.FailureReason.Get()
}

// GetFailureReasonOk returns a tuple with the FailureReason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryBackupInfo) GetFailureReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailureReason.Get(), o.FailureReason.IsSet()
}

// SetFailureReason sets field value
func (o *HistoryBackupInfo) SetFailureReason(v string) {
	o.FailureReason.Set(&v)
}

// GetDetails returns the Details field value
func (o *HistoryBackupInfo) GetDetails() []HistoryBackupSnapshotInfo {
	if o == nil {
		var ret []HistoryBackupSnapshotInfo
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *HistoryBackupInfo) GetDetailsOk() ([]HistoryBackupSnapshotInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Details, true
}

// SetDetails sets field value
func (o *HistoryBackupInfo) SetDetails(v []HistoryBackupSnapshotInfo) {
	o.Details = v
}

func (o HistoryBackupInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HistoryBackupInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backupId"] = o.BackupId
	toSerialize["state"] = o.State
	toSerialize["failureReason"] = o.FailureReason.Get()
	toSerialize["details"] = o.Details
	return toSerialize, nil
}

func (o *HistoryBackupInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backupId",
		"state",
		"failureReason",
		"details",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHistoryBackupInfo := _HistoryBackupInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHistoryBackupInfo)

	if err != nil {
		return err
	}

	*o = HistoryBackupInfo(varHistoryBackupInfo)

	return err
}

type NullableHistoryBackupInfo struct {
	value *HistoryBackupInfo
	isSet bool
}

func (v NullableHistoryBackupInfo) Get() *HistoryBackupInfo {
	return v.value
}

func (v *NullableHistoryBackupInfo) Set(val *HistoryBackupInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableHistoryBackupInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableHistoryBackupInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHistoryBackupInfo(val *HistoryBackupInfo) *NullableHistoryBackupInfo {
	return &NullableHistoryBackupInfo{value: val, isSet: true}
}

func (v NullableHistoryBackupInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHistoryBackupInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
