/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MessageSubscriptionFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageSubscriptionFilter{}

// MessageSubscriptionFilter Message subscription search filter.
type MessageSubscriptionFilter struct {
	// Filter by the business id inherited from the subscribing process instance when the subscription was opened. Supports advanced string filtering, including `$like` with `*`/`?` wildcards.
	BusinessId *StringFilterProperty `json:"businessId,omitempty"`
	// The message subscription key associated with this message subscription.
	MessageSubscriptionKey *MessageSubscriptionKeyFilterProperty `json:"messageSubscriptionKey,omitempty"`
	// The process definition key associated with this correlated message subscription. This only works for data created with 8.9 and later.
	ProcessDefinitionKey *ProcessDefinitionKeyFilterProperty `json:"processDefinitionKey,omitempty"`
	// The process definition ID associated with this message subscription.
	ProcessDefinitionId *StringFilterProperty `json:"processDefinitionId,omitempty"`
	// The process instance key associated with this message subscription.
	ProcessInstanceKey *ProcessInstanceKeyFilterProperty `json:"processInstanceKey,omitempty"`
	// The element ID associated with this message subscription.
	ElementId *StringFilterProperty `json:"elementId,omitempty"`
	// The element instance key associated with this message subscription.
	ElementInstanceKey *ElementInstanceKeyFilterProperty `json:"elementInstanceKey,omitempty"`
	// The message subscription state.
	MessageSubscriptionState *MessageSubscriptionStateFilterProperty `json:"messageSubscriptionState,omitempty"`
	// The last updated date of the message subscription.
	LastUpdatedDate *DateTimeFilterProperty `json:"lastUpdatedDate,omitempty"`
	// The name of the message associated with the message subscription.
	MessageName *StringFilterProperty `json:"messageName,omitempty"`
	// The correlation key of the message subscription.
	CorrelationKey *StringFilterProperty `json:"correlationKey,omitempty"`
	// The unique external tenant ID.
	TenantId *StringFilterProperty `json:"tenantId,omitempty"`
	// The type of message subscription to filter by. When omitted, both `START_EVENT` and `PROCESS_EVENT` are returned. Only available for data created with Camunda 8.10 or later.
	MessageSubscriptionType *MessageSubscriptionTypeFilterProperty `json:"messageSubscriptionType,omitempty"`
	// The name of the process definition associated with this message subscription.
	ProcessDefinitionName *StringFilterProperty `json:"processDefinitionName,omitempty"`
	// The version of the process definition associated with this message subscription.
	ProcessDefinitionVersion *IntegerFilterProperty `json:"processDefinitionVersion,omitempty"`
	// Filter by tool name extracted from the `io.camunda.tool:name` zeebe:property.
	ToolName *StringFilterProperty `json:"toolName,omitempty"`
	// Filter by inbound connector type extracted from the `inbound.type` zeebe:property.
	InboundConnectorType *StringFilterProperty `json:"inboundConnectorType,omitempty"`
}

// NewMessageSubscriptionFilter instantiates a new MessageSubscriptionFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageSubscriptionFilter() *MessageSubscriptionFilter {
	this := MessageSubscriptionFilter{}
	return &this
}

// NewMessageSubscriptionFilterWithDefaults instantiates a new MessageSubscriptionFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageSubscriptionFilterWithDefaults() *MessageSubscriptionFilter {
	this := MessageSubscriptionFilter{}
	return &this
}

// GetBusinessId returns the BusinessId field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetBusinessId() StringFilterProperty {
	if o == nil || IsNil(o.BusinessId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetBusinessIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.BusinessId) {
		return nil, false
	}
	return o.BusinessId, true
}

// HasBusinessId returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasBusinessId() bool {
	if o != nil && !IsNil(o.BusinessId) {
		return true
	}

	return false
}

// SetBusinessId gets a reference to the given StringFilterProperty and assigns it to the BusinessId field.
func (o *MessageSubscriptionFilter) SetBusinessId(v StringFilterProperty) {
	o.BusinessId = &v
}

// GetMessageSubscriptionKey returns the MessageSubscriptionKey field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetMessageSubscriptionKey() MessageSubscriptionKeyFilterProperty {
	if o == nil || IsNil(o.MessageSubscriptionKey) {
		var ret MessageSubscriptionKeyFilterProperty
		return ret
	}
	return *o.MessageSubscriptionKey
}

// GetMessageSubscriptionKeyOk returns a tuple with the MessageSubscriptionKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetMessageSubscriptionKeyOk() (*MessageSubscriptionKeyFilterProperty, bool) {
	if o == nil || IsNil(o.MessageSubscriptionKey) {
		return nil, false
	}
	return o.MessageSubscriptionKey, true
}

// HasMessageSubscriptionKey returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasMessageSubscriptionKey() bool {
	if o != nil && !IsNil(o.MessageSubscriptionKey) {
		return true
	}

	return false
}

// SetMessageSubscriptionKey gets a reference to the given MessageSubscriptionKeyFilterProperty and assigns it to the MessageSubscriptionKey field.
func (o *MessageSubscriptionFilter) SetMessageSubscriptionKey(v MessageSubscriptionKeyFilterProperty) {
	o.MessageSubscriptionKey = &v
}

// GetProcessDefinitionKey returns the ProcessDefinitionKey field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetProcessDefinitionKey() ProcessDefinitionKeyFilterProperty {
	if o == nil || IsNil(o.ProcessDefinitionKey) {
		var ret ProcessDefinitionKeyFilterProperty
		return ret
	}
	return *o.ProcessDefinitionKey
}

// GetProcessDefinitionKeyOk returns a tuple with the ProcessDefinitionKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetProcessDefinitionKeyOk() (*ProcessDefinitionKeyFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessDefinitionKey) {
		return nil, false
	}
	return o.ProcessDefinitionKey, true
}

// HasProcessDefinitionKey returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasProcessDefinitionKey() bool {
	if o != nil && !IsNil(o.ProcessDefinitionKey) {
		return true
	}

	return false
}

// SetProcessDefinitionKey gets a reference to the given ProcessDefinitionKeyFilterProperty and assigns it to the ProcessDefinitionKey field.
func (o *MessageSubscriptionFilter) SetProcessDefinitionKey(v ProcessDefinitionKeyFilterProperty) {
	o.ProcessDefinitionKey = &v
}

// GetProcessDefinitionId returns the ProcessDefinitionId field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetProcessDefinitionId() StringFilterProperty {
	if o == nil || IsNil(o.ProcessDefinitionId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.ProcessDefinitionId
}

// GetProcessDefinitionIdOk returns a tuple with the ProcessDefinitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetProcessDefinitionIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessDefinitionId) {
		return nil, false
	}
	return o.ProcessDefinitionId, true
}

// HasProcessDefinitionId returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasProcessDefinitionId() bool {
	if o != nil && !IsNil(o.ProcessDefinitionId) {
		return true
	}

	return false
}

// SetProcessDefinitionId gets a reference to the given StringFilterProperty and assigns it to the ProcessDefinitionId field.
func (o *MessageSubscriptionFilter) SetProcessDefinitionId(v StringFilterProperty) {
	o.ProcessDefinitionId = &v
}

// GetProcessInstanceKey returns the ProcessInstanceKey field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetProcessInstanceKey() ProcessInstanceKeyFilterProperty {
	if o == nil || IsNil(o.ProcessInstanceKey) {
		var ret ProcessInstanceKeyFilterProperty
		return ret
	}
	return *o.ProcessInstanceKey
}

// GetProcessInstanceKeyOk returns a tuple with the ProcessInstanceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetProcessInstanceKeyOk() (*ProcessInstanceKeyFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessInstanceKey) {
		return nil, false
	}
	return o.ProcessInstanceKey, true
}

// HasProcessInstanceKey returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasProcessInstanceKey() bool {
	if o != nil && !IsNil(o.ProcessInstanceKey) {
		return true
	}

	return false
}

// SetProcessInstanceKey gets a reference to the given ProcessInstanceKeyFilterProperty and assigns it to the ProcessInstanceKey field.
func (o *MessageSubscriptionFilter) SetProcessInstanceKey(v ProcessInstanceKeyFilterProperty) {
	o.ProcessInstanceKey = &v
}

// GetElementId returns the ElementId field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetElementId() StringFilterProperty {
	if o == nil || IsNil(o.ElementId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.ElementId
}

// GetElementIdOk returns a tuple with the ElementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetElementIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.ElementId) {
		return nil, false
	}
	return o.ElementId, true
}

// HasElementId returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasElementId() bool {
	if o != nil && !IsNil(o.ElementId) {
		return true
	}

	return false
}

// SetElementId gets a reference to the given StringFilterProperty and assigns it to the ElementId field.
func (o *MessageSubscriptionFilter) SetElementId(v StringFilterProperty) {
	o.ElementId = &v
}

// GetElementInstanceKey returns the ElementInstanceKey field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetElementInstanceKey() ElementInstanceKeyFilterProperty {
	if o == nil || IsNil(o.ElementInstanceKey) {
		var ret ElementInstanceKeyFilterProperty
		return ret
	}
	return *o.ElementInstanceKey
}

// GetElementInstanceKeyOk returns a tuple with the ElementInstanceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetElementInstanceKeyOk() (*ElementInstanceKeyFilterProperty, bool) {
	if o == nil || IsNil(o.ElementInstanceKey) {
		return nil, false
	}
	return o.ElementInstanceKey, true
}

// HasElementInstanceKey returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasElementInstanceKey() bool {
	if o != nil && !IsNil(o.ElementInstanceKey) {
		return true
	}

	return false
}

// SetElementInstanceKey gets a reference to the given ElementInstanceKeyFilterProperty and assigns it to the ElementInstanceKey field.
func (o *MessageSubscriptionFilter) SetElementInstanceKey(v ElementInstanceKeyFilterProperty) {
	o.ElementInstanceKey = &v
}

// GetMessageSubscriptionState returns the MessageSubscriptionState field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetMessageSubscriptionState() MessageSubscriptionStateFilterProperty {
	if o == nil || IsNil(o.MessageSubscriptionState) {
		var ret MessageSubscriptionStateFilterProperty
		return ret
	}
	return *o.MessageSubscriptionState
}

// GetMessageSubscriptionStateOk returns a tuple with the MessageSubscriptionState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetMessageSubscriptionStateOk() (*MessageSubscriptionStateFilterProperty, bool) {
	if o == nil || IsNil(o.MessageSubscriptionState) {
		return nil, false
	}
	return o.MessageSubscriptionState, true
}

// HasMessageSubscriptionState returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasMessageSubscriptionState() bool {
	if o != nil && !IsNil(o.MessageSubscriptionState) {
		return true
	}

	return false
}

// SetMessageSubscriptionState gets a reference to the given MessageSubscriptionStateFilterProperty and assigns it to the MessageSubscriptionState field.
func (o *MessageSubscriptionFilter) SetMessageSubscriptionState(v MessageSubscriptionStateFilterProperty) {
	o.MessageSubscriptionState = &v
}

// GetLastUpdatedDate returns the LastUpdatedDate field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetLastUpdatedDate() DateTimeFilterProperty {
	if o == nil || IsNil(o.LastUpdatedDate) {
		var ret DateTimeFilterProperty
		return ret
	}
	return *o.LastUpdatedDate
}

// GetLastUpdatedDateOk returns a tuple with the LastUpdatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetLastUpdatedDateOk() (*DateTimeFilterProperty, bool) {
	if o == nil || IsNil(o.LastUpdatedDate) {
		return nil, false
	}
	return o.LastUpdatedDate, true
}

// HasLastUpdatedDate returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasLastUpdatedDate() bool {
	if o != nil && !IsNil(o.LastUpdatedDate) {
		return true
	}

	return false
}

// SetLastUpdatedDate gets a reference to the given DateTimeFilterProperty and assigns it to the LastUpdatedDate field.
func (o *MessageSubscriptionFilter) SetLastUpdatedDate(v DateTimeFilterProperty) {
	o.LastUpdatedDate = &v
}

// GetMessageName returns the MessageName field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetMessageName() StringFilterProperty {
	if o == nil || IsNil(o.MessageName) {
		var ret StringFilterProperty
		return ret
	}
	return *o.MessageName
}

// GetMessageNameOk returns a tuple with the MessageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetMessageNameOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.MessageName) {
		return nil, false
	}
	return o.MessageName, true
}

// HasMessageName returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasMessageName() bool {
	if o != nil && !IsNil(o.MessageName) {
		return true
	}

	return false
}

// SetMessageName gets a reference to the given StringFilterProperty and assigns it to the MessageName field.
func (o *MessageSubscriptionFilter) SetMessageName(v StringFilterProperty) {
	o.MessageName = &v
}

// GetCorrelationKey returns the CorrelationKey field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetCorrelationKey() StringFilterProperty {
	if o == nil || IsNil(o.CorrelationKey) {
		var ret StringFilterProperty
		return ret
	}
	return *o.CorrelationKey
}

// GetCorrelationKeyOk returns a tuple with the CorrelationKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetCorrelationKeyOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.CorrelationKey) {
		return nil, false
	}
	return o.CorrelationKey, true
}

// HasCorrelationKey returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasCorrelationKey() bool {
	if o != nil && !IsNil(o.CorrelationKey) {
		return true
	}

	return false
}

// SetCorrelationKey gets a reference to the given StringFilterProperty and assigns it to the CorrelationKey field.
func (o *MessageSubscriptionFilter) SetCorrelationKey(v StringFilterProperty) {
	o.CorrelationKey = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetTenantId() StringFilterProperty {
	if o == nil || IsNil(o.TenantId) {
		var ret StringFilterProperty
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetTenantIdOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given StringFilterProperty and assigns it to the TenantId field.
func (o *MessageSubscriptionFilter) SetTenantId(v StringFilterProperty) {
	o.TenantId = &v
}

// GetMessageSubscriptionType returns the MessageSubscriptionType field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetMessageSubscriptionType() MessageSubscriptionTypeFilterProperty {
	if o == nil || IsNil(o.MessageSubscriptionType) {
		var ret MessageSubscriptionTypeFilterProperty
		return ret
	}
	return *o.MessageSubscriptionType
}

// GetMessageSubscriptionTypeOk returns a tuple with the MessageSubscriptionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetMessageSubscriptionTypeOk() (*MessageSubscriptionTypeFilterProperty, bool) {
	if o == nil || IsNil(o.MessageSubscriptionType) {
		return nil, false
	}
	return o.MessageSubscriptionType, true
}

// HasMessageSubscriptionType returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasMessageSubscriptionType() bool {
	if o != nil && !IsNil(o.MessageSubscriptionType) {
		return true
	}

	return false
}

// SetMessageSubscriptionType gets a reference to the given MessageSubscriptionTypeFilterProperty and assigns it to the MessageSubscriptionType field.
func (o *MessageSubscriptionFilter) SetMessageSubscriptionType(v MessageSubscriptionTypeFilterProperty) {
	o.MessageSubscriptionType = &v
}

// GetProcessDefinitionName returns the ProcessDefinitionName field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetProcessDefinitionName() StringFilterProperty {
	if o == nil || IsNil(o.ProcessDefinitionName) {
		var ret StringFilterProperty
		return ret
	}
	return *o.ProcessDefinitionName
}

// GetProcessDefinitionNameOk returns a tuple with the ProcessDefinitionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetProcessDefinitionNameOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessDefinitionName) {
		return nil, false
	}
	return o.ProcessDefinitionName, true
}

// HasProcessDefinitionName returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasProcessDefinitionName() bool {
	if o != nil && !IsNil(o.ProcessDefinitionName) {
		return true
	}

	return false
}

// SetProcessDefinitionName gets a reference to the given StringFilterProperty and assigns it to the ProcessDefinitionName field.
func (o *MessageSubscriptionFilter) SetProcessDefinitionName(v StringFilterProperty) {
	o.ProcessDefinitionName = &v
}

// GetProcessDefinitionVersion returns the ProcessDefinitionVersion field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetProcessDefinitionVersion() IntegerFilterProperty {
	if o == nil || IsNil(o.ProcessDefinitionVersion) {
		var ret IntegerFilterProperty
		return ret
	}
	return *o.ProcessDefinitionVersion
}

// GetProcessDefinitionVersionOk returns a tuple with the ProcessDefinitionVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetProcessDefinitionVersionOk() (*IntegerFilterProperty, bool) {
	if o == nil || IsNil(o.ProcessDefinitionVersion) {
		return nil, false
	}
	return o.ProcessDefinitionVersion, true
}

// HasProcessDefinitionVersion returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasProcessDefinitionVersion() bool {
	if o != nil && !IsNil(o.ProcessDefinitionVersion) {
		return true
	}

	return false
}

// SetProcessDefinitionVersion gets a reference to the given IntegerFilterProperty and assigns it to the ProcessDefinitionVersion field.
func (o *MessageSubscriptionFilter) SetProcessDefinitionVersion(v IntegerFilterProperty) {
	o.ProcessDefinitionVersion = &v
}

// GetToolName returns the ToolName field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetToolName() StringFilterProperty {
	if o == nil || IsNil(o.ToolName) {
		var ret StringFilterProperty
		return ret
	}
	return *o.ToolName
}

// GetToolNameOk returns a tuple with the ToolName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetToolNameOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.ToolName) {
		return nil, false
	}
	return o.ToolName, true
}

// HasToolName returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasToolName() bool {
	if o != nil && !IsNil(o.ToolName) {
		return true
	}

	return false
}

// SetToolName gets a reference to the given StringFilterProperty and assigns it to the ToolName field.
func (o *MessageSubscriptionFilter) SetToolName(v StringFilterProperty) {
	o.ToolName = &v
}

// GetInboundConnectorType returns the InboundConnectorType field value if set, zero value otherwise.
func (o *MessageSubscriptionFilter) GetInboundConnectorType() StringFilterProperty {
	if o == nil || IsNil(o.InboundConnectorType) {
		var ret StringFilterProperty
		return ret
	}
	return *o.InboundConnectorType
}

// GetInboundConnectorTypeOk returns a tuple with the InboundConnectorType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSubscriptionFilter) GetInboundConnectorTypeOk() (*StringFilterProperty, bool) {
	if o == nil || IsNil(o.InboundConnectorType) {
		return nil, false
	}
	return o.InboundConnectorType, true
}

// HasInboundConnectorType returns a boolean if a field has been set.
func (o *MessageSubscriptionFilter) HasInboundConnectorType() bool {
	if o != nil && !IsNil(o.InboundConnectorType) {
		return true
	}

	return false
}

// SetInboundConnectorType gets a reference to the given StringFilterProperty and assigns it to the InboundConnectorType field.
func (o *MessageSubscriptionFilter) SetInboundConnectorType(v StringFilterProperty) {
	o.InboundConnectorType = &v
}

func (o MessageSubscriptionFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageSubscriptionFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BusinessId) {
		toSerialize["businessId"] = o.BusinessId
	}
	if !IsNil(o.MessageSubscriptionKey) {
		toSerialize["messageSubscriptionKey"] = o.MessageSubscriptionKey
	}
	if !IsNil(o.ProcessDefinitionKey) {
		toSerialize["processDefinitionKey"] = o.ProcessDefinitionKey
	}
	if !IsNil(o.ProcessDefinitionId) {
		toSerialize["processDefinitionId"] = o.ProcessDefinitionId
	}
	if !IsNil(o.ProcessInstanceKey) {
		toSerialize["processInstanceKey"] = o.ProcessInstanceKey
	}
	if !IsNil(o.ElementId) {
		toSerialize["elementId"] = o.ElementId
	}
	if !IsNil(o.ElementInstanceKey) {
		toSerialize["elementInstanceKey"] = o.ElementInstanceKey
	}
	if !IsNil(o.MessageSubscriptionState) {
		toSerialize["messageSubscriptionState"] = o.MessageSubscriptionState
	}
	if !IsNil(o.LastUpdatedDate) {
		toSerialize["lastUpdatedDate"] = o.LastUpdatedDate
	}
	if !IsNil(o.MessageName) {
		toSerialize["messageName"] = o.MessageName
	}
	if !IsNil(o.CorrelationKey) {
		toSerialize["correlationKey"] = o.CorrelationKey
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.MessageSubscriptionType) {
		toSerialize["messageSubscriptionType"] = o.MessageSubscriptionType
	}
	if !IsNil(o.ProcessDefinitionName) {
		toSerialize["processDefinitionName"] = o.ProcessDefinitionName
	}
	if !IsNil(o.ProcessDefinitionVersion) {
		toSerialize["processDefinitionVersion"] = o.ProcessDefinitionVersion
	}
	if !IsNil(o.ToolName) {
		toSerialize["toolName"] = o.ToolName
	}
	if !IsNil(o.InboundConnectorType) {
		toSerialize["inboundConnectorType"] = o.InboundConnectorType
	}
	return toSerialize, nil
}

type NullableMessageSubscriptionFilter struct {
	value *MessageSubscriptionFilter
	isSet bool
}

func (v NullableMessageSubscriptionFilter) Get() *MessageSubscriptionFilter {
	return v.value
}

func (v *NullableMessageSubscriptionFilter) Set(val *MessageSubscriptionFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageSubscriptionFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageSubscriptionFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageSubscriptionFilter(val *MessageSubscriptionFilter) *NullableMessageSubscriptionFilter {
	return &NullableMessageSubscriptionFilter{value: val, isSet: true}
}

func (v NullableMessageSubscriptionFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageSubscriptionFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
