/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchOperationSearchQuerySortRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchOperationSearchQuerySortRequest{}

// BatchOperationSearchQuerySortRequest struct for BatchOperationSearchQuerySortRequest
type BatchOperationSearchQuerySortRequest struct {
	// The field to sort by.
	Field string         `json:"field"`
	Order *SortOrderEnum `json:"order,omitempty"`
}

type _BatchOperationSearchQuerySortRequest BatchOperationSearchQuerySortRequest

// NewBatchOperationSearchQuerySortRequest instantiates a new BatchOperationSearchQuerySortRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchOperationSearchQuerySortRequest(field string) *BatchOperationSearchQuerySortRequest {
	this := BatchOperationSearchQuerySortRequest{}
	this.Field = field
	var order SortOrderEnum = SORTORDERENUM_ASC
	this.Order = &order
	return &this
}

// NewBatchOperationSearchQuerySortRequestWithDefaults instantiates a new BatchOperationSearchQuerySortRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchOperationSearchQuerySortRequestWithDefaults() *BatchOperationSearchQuerySortRequest {
	this := BatchOperationSearchQuerySortRequest{}
	var order SortOrderEnum = SORTORDERENUM_ASC
	this.Order = &order
	return &this
}

// GetField returns the Field field value
func (o *BatchOperationSearchQuerySortRequest) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *BatchOperationSearchQuerySortRequest) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *BatchOperationSearchQuerySortRequest) SetField(v string) {
	o.Field = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *BatchOperationSearchQuerySortRequest) GetOrder() SortOrderEnum {
	if o == nil || IsNil(o.Order) {
		var ret SortOrderEnum
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchOperationSearchQuerySortRequest) GetOrderOk() (*SortOrderEnum, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *BatchOperationSearchQuerySortRequest) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given SortOrderEnum and assigns it to the Order field.
func (o *BatchOperationSearchQuerySortRequest) SetOrder(v SortOrderEnum) {
	o.Order = &v
}

func (o BatchOperationSearchQuerySortRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchOperationSearchQuerySortRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

func (o *BatchOperationSearchQuerySortRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchOperationSearchQuerySortRequest := _BatchOperationSearchQuerySortRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchOperationSearchQuerySortRequest)

	if err != nil {
		return err
	}

	*o = BatchOperationSearchQuerySortRequest(varBatchOperationSearchQuerySortRequest)

	return err
}

type NullableBatchOperationSearchQuerySortRequest struct {
	value *BatchOperationSearchQuerySortRequest
	isSet bool
}

func (v NullableBatchOperationSearchQuerySortRequest) Get() *BatchOperationSearchQuerySortRequest {
	return v.value
}

func (v *NullableBatchOperationSearchQuerySortRequest) Set(val *BatchOperationSearchQuerySortRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchOperationSearchQuerySortRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchOperationSearchQuerySortRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchOperationSearchQuerySortRequest(val *BatchOperationSearchQuerySortRequest) *NullableBatchOperationSearchQuerySortRequest {
	return &NullableBatchOperationSearchQuerySortRequest{value: val, isSet: true}
}

func (v NullableBatchOperationSearchQuerySortRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchOperationSearchQuerySortRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
