/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateClusterVariableRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClusterVariableRequest{}

// CreateClusterVariableRequest struct for CreateClusterVariableRequest
type CreateClusterVariableRequest struct {
	// The name of the cluster variable. Must be unique within its scope (global or tenant-specific).
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9_~@.+-]+$"`
	// The value of the cluster variable. Can be any JSON object or primitive value. Will be serialized as a JSON string in responses.
	Value map[string]interface{} `json:"value"`
	// A generic key-value metadata bag attached to the cluster variable. Values must be strings or numbers. Limited to 100 entries and a configurable maximum serialized size (default: 100 entries at max key length of a cluster variable name (256 chars) plus the maximum value length, 8192 characters).
	Metadata map[string]CreateClusterVariableRequestMetadataValue `json:"metadata,omitempty"`
	// The kind of the cluster variable. Defaults to JSON if not specified.
	Kind *ClusterVariableKindEnum `json:"kind,omitempty"`
}

type _CreateClusterVariableRequest CreateClusterVariableRequest

// NewCreateClusterVariableRequest instantiates a new CreateClusterVariableRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterVariableRequest(name string, value map[string]interface{}) *CreateClusterVariableRequest {
	this := CreateClusterVariableRequest{}
	this.Name = name
	this.Value = value
	return &this
}

// NewCreateClusterVariableRequestWithDefaults instantiates a new CreateClusterVariableRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterVariableRequestWithDefaults() *CreateClusterVariableRequest {
	this := CreateClusterVariableRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateClusterVariableRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateClusterVariableRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateClusterVariableRequest) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *CreateClusterVariableRequest) GetValue() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CreateClusterVariableRequest) GetValueOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *CreateClusterVariableRequest) SetValue(v map[string]interface{}) {
	o.Value = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateClusterVariableRequest) GetMetadata() map[string]CreateClusterVariableRequestMetadataValue {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]CreateClusterVariableRequestMetadataValue
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterVariableRequest) GetMetadataOk() (map[string]CreateClusterVariableRequestMetadataValue, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]CreateClusterVariableRequestMetadataValue{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateClusterVariableRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]CreateClusterVariableRequestMetadataValue and assigns it to the Metadata field.
func (o *CreateClusterVariableRequest) SetMetadata(v map[string]CreateClusterVariableRequestMetadataValue) {
	o.Metadata = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *CreateClusterVariableRequest) GetKind() ClusterVariableKindEnum {
	if o == nil || IsNil(o.Kind) {
		var ret ClusterVariableKindEnum
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterVariableRequest) GetKindOk() (*ClusterVariableKindEnum, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *CreateClusterVariableRequest) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given ClusterVariableKindEnum and assigns it to the Kind field.
func (o *CreateClusterVariableRequest) SetKind(v ClusterVariableKindEnum) {
	o.Kind = &v
}

func (o CreateClusterVariableRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClusterVariableRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	return toSerialize, nil
}

func (o *CreateClusterVariableRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateClusterVariableRequest := _CreateClusterVariableRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateClusterVariableRequest)

	if err != nil {
		return err
	}

	*o = CreateClusterVariableRequest(varCreateClusterVariableRequest)

	return err
}

type NullableCreateClusterVariableRequest struct {
	value *CreateClusterVariableRequest
	isSet bool
}

func (v NullableCreateClusterVariableRequest) Get() *CreateClusterVariableRequest {
	return v.value
}

func (v *NullableCreateClusterVariableRequest) Set(val *CreateClusterVariableRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClusterVariableRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClusterVariableRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClusterVariableRequest(val *CreateClusterVariableRequest) *NullableCreateClusterVariableRequest {
	return &NullableCreateClusterVariableRequest{value: val, isSet: true}
}

func (v NullableCreateClusterVariableRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClusterVariableRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
