/*
Orchestration Cluster API

API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VariableValueFilterProperty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VariableValueFilterProperty{}

// VariableValueFilterProperty struct for VariableValueFilterProperty
type VariableValueFilterProperty struct {
	// Name of the variable.
	Name string `json:"name"`
	// The value of the variable. Variable values in filters need to be in serialized JSON format. For example, a variable with string value `myValue` can be found with the filter value `\"myValue\"`. Consider appropriate escaping for special characters in JSON strings when constructing filter values.
	Value StringFilterProperty `json:"value"`
}

type _VariableValueFilterProperty VariableValueFilterProperty

// NewVariableValueFilterProperty instantiates a new VariableValueFilterProperty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariableValueFilterProperty(name string, value StringFilterProperty) *VariableValueFilterProperty {
	this := VariableValueFilterProperty{}
	this.Name = name
	this.Value = value
	return &this
}

// NewVariableValueFilterPropertyWithDefaults instantiates a new VariableValueFilterProperty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariableValueFilterPropertyWithDefaults() *VariableValueFilterProperty {
	this := VariableValueFilterProperty{}
	return &this
}

// GetName returns the Name field value
func (o *VariableValueFilterProperty) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VariableValueFilterProperty) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VariableValueFilterProperty) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *VariableValueFilterProperty) GetValue() StringFilterProperty {
	if o == nil {
		var ret StringFilterProperty
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *VariableValueFilterProperty) GetValueOk() (*StringFilterProperty, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *VariableValueFilterProperty) SetValue(v StringFilterProperty) {
	o.Value = v
}

func (o VariableValueFilterProperty) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VariableValueFilterProperty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *VariableValueFilterProperty) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVariableValueFilterProperty := _VariableValueFilterProperty{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVariableValueFilterProperty)

	if err != nil {
		return err
	}

	*o = VariableValueFilterProperty(varVariableValueFilterProperty)

	return err
}

type NullableVariableValueFilterProperty struct {
	value *VariableValueFilterProperty
	isSet bool
}

func (v NullableVariableValueFilterProperty) Get() *VariableValueFilterProperty {
	return v.value
}

func (v *NullableVariableValueFilterProperty) Set(val *VariableValueFilterProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableVariableValueFilterProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableVariableValueFilterProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariableValueFilterProperty(val *VariableValueFilterProperty) *NullableVariableValueFilterProperty {
	return &NullableVariableValueFilterProperty{value: val, isSet: true}
}

func (v NullableVariableValueFilterProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariableValueFilterProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
