// Code generated by scripts/hooks/hook_02_union_exact_match.py. DO NOT EDIT.

package openapi

// *ExactMatch union branches are exact-value matches on a semantic key. Each is
// an alias to its base key type (hook 01) so the generated union structs compile
// and (un)marshal as the underlying scalar.
type AuditLogEntityKeyExactMatch = AuditLogEntityKey
type DecisionEvaluationInstanceKeyExactMatch = DecisionEvaluationInstanceKey
type ElementIdExactMatch = ElementId
type ProcessDefinitionIdExactMatch = ProcessDefinitionId
