"""Hook 07 — dependent-presence couplings declared with `x-present-when`.

OpenAPI 3.x cannot say that a response field is present only when the request set a
particular flag, so the specification states it out of band: a field-level
`x-present-when: {request: <flag>, equals: true}` marker on the conditional field
(upstream camunda/camunda#62777, applied to `ActivatedJobResult.jobLeaseToken`).

Go has no dependent typing, so the guarantee has to live in the hand-written runtime.
This hook emits the coupling as data in the root `camunda` package so that runtime
enforces what the specification declares rather than a relationship hardcoded from
memory: if upstream renames the flag, moves the field, or adds a second conditional
field, the generated table changes and the guards in presentwhen_test.go fail.

Deliberately generic over the number of markers. A second `x-present-when` field is
carried into the table automatically, and the enforcement guard — not this hook — is
what reports that the runtime has not absorbed it yet.
"""
from __future__ import annotations

import json
from pathlib import Path

HEADER = "// Code generated by scripts/hooks/hook_07_present_when.py. DO NOT EDIT.\n\n"


def _quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def run(ctx) -> None:
    root: Path = ctx["root"]
    spec = json.loads(Path(ctx["spec_path"]).read_text(encoding="utf-8"))
    schemas = (spec.get("components") or {}).get("schemas") or {}

    couplings = []
    for schema_name, schema in sorted(schemas.items()):
        if not isinstance(schema, dict):
            continue
        for field_name, field in sorted((schema.get("properties") or {}).items()):
            if not isinstance(field, dict):
                continue
            # Key presence, not truthiness: an explicit `x-present-when: null` is a
            # malformed marker, and `.get()` would let it masquerade as an absent one
            # and be skipped, so the runtime would drift from a spec that meant to
            # declare a coupling. Let it reach the validation below and fail loudly.
            if "x-present-when" not in field:
                continue
            marker = field["x-present-when"]
            if not isinstance(marker, dict) or not marker.get("request") or marker.get("equals") is not True:
                raise SystemExit(
                    "hook 07: x-present-when on {}.{} is {!r}, which is not the "
                    "'present when <flag> is true' shape the runtime guards are built on. "
                    "Teach this hook the new shape rather than dropping the marker.".format(
                        schema_name, field_name, marker
                    )
                )
            couplings.append((schema_name, field_name, marker["request"]))

    if not couplings:
        raise SystemExit(
            "hook 07: the bundled spec declares no x-present-when markers. Either the "
            "bundler is stripping the vendor key or upstream removed it; emitting an empty "
            "table would silently retire the runtime guards built on it."
        )

    lines = [HEADER, "package camunda\n\n"]
    lines.append("// presentWhenCoupling is a dependent-presence relationship the specification\n")
    lines.append("// declares with x-present-when: ResponseSchema.ResponseField is present exactly\n")
    lines.append("// when the request set RequestFlag. OpenAPI cannot express this, so the runtime\n")
    lines.append("// carries it and this table is the evidence it still matches the specification.\n")
    lines.append("type presentWhenCoupling struct {\n")
    lines.append("\tResponseSchema string\n")
    lines.append("\tResponseField  string\n")
    lines.append("\tRequestFlag    string\n")
    lines.append("}\n\n")
    lines.append("// presentWhenCouplings is ordered by schema then field, so the table is stable\n")
    lines.append("// across regenerations.\n")
    lines.append("var presentWhenCouplings = []presentWhenCoupling{\n")
    for schema_name, field_name, flag in couplings:
        lines.append("\t{\n")
        lines.append(f"\t\tResponseSchema: {_quote(schema_name)},\n")
        lines.append(f"\t\tResponseField:  {_quote(field_name)},\n")
        lines.append(f"\t\tRequestFlag:    {_quote(flag)},\n")
        lines.append("\t},\n")
    lines.append("}\n")

    out = root / "presentwhen_generated.go"
    out.write_text("".join(lines), encoding="utf-8")
    print(f"hook_07_present_when: emitted {len(couplings)} coupling(s) into {out.name}")
